import type { User, GameDefinition, GachaCard, RankingEntry, ShopItem } from './types';

export const MOCK_USER: User = {
  id: 'user-001',
  nickname: 'さとる',
  classId: 'basic',
  avatarUrl: '',
  avatarType: 'boy',
  equippedAvatarId: null,
  purchasedAvatarIds: [],
  titleId: 'beginner',
  level: 5,
  totalAlt: 1240,
  currentAlt: 1240,
  streakDays: 7,
  lastLogin: new Date().toISOString(),
  createdAt: '2025-01-01T00:00:00Z',
};

export const MOCK_GAMES: GameDefinition[] = [
  {
    id: 'number-tap',
    title: '数字タップゲーム',
    description: '画面に表示される数字を順番にタップしよう！',
    category: 'math',
    difficulty: 1,
    thumbnail: '',
    altReward: 10,
    estimatedMinutes: 2,
    emoji: '🔢',
  },
  {
    id: 'fraction-fusion',
    title: '分数フュージョン',
    description: '分数を合わせて目標の数を作ろう！',
    category: 'math',
    difficulty: 3,
    thumbnail: '',
    altReward: 15,
    estimatedMinutes: 3,
    emoji: '➗',
  },
  {
    id: 'japan-map-quiz',
    title: '日本地図クイズ',
    description: '都道府県の位置を当てよう！',
    category: 'social',
    difficulty: 2,
    thumbnail: '',
    altReward: 10,
    estimatedMinutes: 3,
    emoji: '🗾',
  },
  {
    id: 'math-battle',
    title: '算数バトル',
    description: '計算問題を素早く解いてスコアを稼ごう！',
    category: 'puzzle',
    difficulty: 2,
    thumbnail: '',
    altReward: 10,
    estimatedMinutes: 2,
    emoji: '⚔️',
  },
  {
    id: 'kotowaza-drop',
    title: 'ことわざドロップ',
    description: 'ことわざの穴埋めに挑戦！',
    category: 'japanese',
    difficulty: 2,
    thumbnail: '',
    altReward: 10,
    estimatedMinutes: 3,
    emoji: '📝',
  },
  {
    id: 'history-karuta',
    title: '歴史カルタ',
    description: '歴史上の人物や出来事をカルタで学ぼう！',
    category: 'social',
    difficulty: 3,
    thumbnail: '',
    altReward: 15,
    estimatedMinutes: 5,
    emoji: '🏯',
  },
  {
    id: 'science-team',
    title: '編成チーム',
    description: '科学者チームを編成してミッションに挑もう！',
    category: 'science',
    difficulty: 3,
    thumbnail: '',
    altReward: 20,
    estimatedMinutes: 5,
    emoji: '🔬',
  },
  {
    id: 'inquiry-quest',
    title: '探究クエスト',
    description: '不思議な謎を解き明かそう！',
    category: 'inquiry',
    difficulty: 4,
    thumbnail: '',
    altReward: 25,
    estimatedMinutes: 10,
    emoji: '💡',
  },
];

export const MOCK_CARDS: GachaCard[] = [
  { id: 'c001', name: '織田信長', category: 'great_person', rarity: 5, description: '戦国時代の革命児。天下統一を目指した武将。', imageUrl: '', era: '1534-1582' },
  { id: 'c002', name: 'マリー・キュリー', category: 'great_person', rarity: 4, description: '放射能の研究でノーベル賞を2度受賞した科学者。', imageUrl: '', era: '1867-1934' },
  { id: 'c003', name: 'カブトムシ', category: 'creature', rarity: 1, description: '日本の夏の定番。角が自慢の甲虫。', imageUrl: '' },
  { id: 'c004', name: 'クジラ', category: 'creature', rarity: 3, description: '地球最大の哺乳類。海の王者。', imageUrl: '' },
  { id: 'c005', name: '万里の長城', category: 'heritage', rarity: 4, description: '中国の巨大な防壁。世界遺産。', imageUrl: '' },
  { id: 'c006', name: 'コロッセオ', category: 'heritage', rarity: 3, description: '古代ローマの円形闘技場。', imageUrl: '' },
  { id: 'c007', name: '電球', category: 'invention', rarity: 2, description: 'エジソンが実用化した照明器具。', imageUrl: '' },
  { id: 'c008', name: 'インターネット', category: 'invention', rarity: 5, description: '世界を変えた情報通信技術。', imageUrl: '' },
  { id: 'c009', name: 'クエスくん', category: 'trail', rarity: 6, description: 'TRAIL QUEST WORLDの伝説のマスコット！', imageUrl: '' },
  { id: 'c010', name: 'タンQちゃん', category: 'trail', rarity: 2, description: '探究心あふれるかわいいキャラクター。', imageUrl: '' },
  { id: 'c011', name: 'レオナルド・ダ・ヴィンチ', category: 'great_person', rarity: 6, description: '万能の天才。芸術家にして科学者。', imageUrl: '', era: '1452-1519' },
  { id: 'c012', name: '徳川家康', category: 'great_person', rarity: 4, description: '江戸幕府を開いた征夷大将軍。', imageUrl: '', era: '1543-1616' },
  { id: 'c013', name: 'アインシュタイン', category: 'great_person', rarity: 5, description: '相対性理論を発表した天才物理学者。', imageUrl: '', era: '1879-1955' },
  { id: 'c014', name: 'ドラゴン', category: 'creature', rarity: 5, description: '伝説の火を吐く竜。', imageUrl: '' },
  { id: 'c015', name: 'ユニコーン', category: 'creature', rarity: 3, description: '一角獣。純粋さの象徴。', imageUrl: '' },
  { id: 'c016', name: 'ピラミッド', category: 'heritage', rarity: 3, description: 'エジプトの巨大建造物。', imageUrl: '' },
  { id: 'c017', name: '活版印刷', category: 'invention', rarity: 2, description: 'グーテンベルクが発明した印刷技術。', imageUrl: '' },
  { id: 'c018', name: '蒸気機関', category: 'invention', rarity: 3, description: '産業革命を起こした動力源。', imageUrl: '' },
  { id: 'c019', name: 'フェニックス', category: 'creature', rarity: 4, description: '不死鳥。炎から蘇る伝説の鳥。', imageUrl: '' },
  { id: 'c020', name: '九尾の狐', category: 'creature', rarity: 5, description: '九本の尻尾を持つ妖狐。', imageUrl: '' },
];

// Daily Missions
export const MOCK_DAILY_MISSIONS = [
  { id: 'mission-001', title: 'ゲームを3回クリア', description: 'ゲームを3回クリアしよう', reward: 15, category: 'game', progress: 1, target: 3 },
  { id: 'mission-002', title: 'ガチャを1回引く', description: 'ノーマルガチャを1回引こう', reward: 10, category: 'gacha', progress: 0, target: 1 },
  { id: 'mission-003', title: 'カードをコレクションで確認', description: 'コレクション画面でカードを確認しよう', reward: 5, category: 'collection', progress: 0, target: 1 },
  { id: 'mission-004', title: 'プレミアムガチャを1回引く', description: 'プレミアムガチャに挑戦しよう', reward: 20, category: 'gacha', progress: 0, target: 1 },
  { id: 'mission-005', title: 'SR以上を引く', description: 'SR以上のレアカードを引こう', reward: 30, category: 'gacha', progress: 0, target: 1 },
];

export const MOCK_RANKINGS: RankingEntry[] = [
  { rank: 1, userId: 'u1', nickname: 'いけだ', avatarUrl: '', score: 520, level: 8 },
  { rank: 2, userId: 'u2', nickname: 'あおら', avatarUrl: '', score: 380, level: 6 },
  { rank: 3, userId: 'u3', nickname: 'たかぎ', avatarUrl: '', score: 210, level: 5 },
  { rank: 4, userId: 'u4', nickname: 'みやもと', avatarUrl: '', score: 170, level: 4 },
  { rank: 5, userId: 'u5', nickname: 'やまだ', avatarUrl: '', score: 150, level: 4 },
  { rank: 6, userId: 'u6', nickname: 'すずき', avatarUrl: '', score: 130, level: 3 },
  { rank: 7, userId: 'u7', nickname: 'たなか', avatarUrl: '', score: 110, level: 3 },
  { rank: 8, userId: 'u8', nickname: 'さとう', avatarUrl: '', score: 90, level: 2 },
  { rank: 9, userId: 'u9', nickname: 'わたなべ', avatarUrl: '', score: 70, level: 2 },
  { rank: 10, userId: 'u10', nickname: 'いとう', avatarUrl: '', score: 50, level: 1 },
];

export const MOCK_SHOP_ITEMS: ShopItem[] = [
  // --- かわいい・ポップ・動物系（低学年向け） ---
  { id: 'avatar-princess-chibi', name: '姫', category: 'avatar', price: 700, imageUrl: '', description: 'キュートな姫のアバター', owned: false },
  { id: 'avatar-catgirl', name: '猫耳少女', category: 'avatar', price: 500, imageUrl: '', description: 'すばしっこい猫耳冒険者のアバター', owned: false },
  { id: 'avatar-snow-rabbit', name: '雪うさぎ', category: 'avatar', price: 500, imageUrl: '', description: '雪と氷の魔法を使ううさぎ耳の少女のアバター', owned: false },
  { id: 'avatar-fairy', name: '妖精', category: 'avatar', price: 600, imageUrl: '', description: '花と蝶の妖精のアバター', owned: false },
  { id: 'avatar-flower-spirit', name: '花の精霊', category: 'avatar', price: 550, imageUrl: '', description: '花と蔓の力を操る精霊のアバター', owned: false },
  { id: 'avatar-angel-chibi', name: '天使', category: 'avatar', price: 450, imageUrl: '', description: 'キュートな天使のアバター', owned: false },
  { id: 'avatar-beast-tamer', name: '魔獣使い', category: 'avatar', price: 650, imageUrl: '', description: '魔獣を手懐ける勇敢な魔獣使いのアバター', owned: false },
  { id: 'avatar-herbalist', name: '薬草師', category: 'avatar', price: 550, imageUrl: '', description: '癒しの薬草を操る薬草師のアバター', owned: false },
  { id: 'avatar-mermaid', name: '人魚', category: 'avatar', price: 650, imageUrl: '', description: '海の人魚姫のアバター', owned: false },
  { id: 'avatar-dancer', name: '踊り子', category: 'avatar', price: 500, imageUrl: '', description: '華麗な舞で味方を鼓舞する踊り子のアバター', owned: false },
  // --- ポップ・ファンタジー（中低学年向け） ---
  { id: 'avatar-witch-chibi', name: '魔女', category: 'avatar', price: 500, imageUrl: '', description: 'キュートな魔女のアバター', owned: false },
  { id: 'avatar-songstress', name: '歌姫', category: 'avatar', price: 650, imageUrl: '', description: '歌声で魔法を紡ぐ歌姫のアバター', owned: false },
  { id: 'avatar-miko', name: '巫女', category: 'avatar', price: 600, imageUrl: '', description: '神聖な力で邪を祓う巫女のアバター', owned: false },
  { id: 'avatar-priest', name: '僧侶', category: 'avatar', price: 550, imageUrl: '', description: '聖なる光で仲間を癒す僧侶のアバター', owned: false },
  { id: 'avatar-wind-mage', name: '風の使い', category: 'avatar', price: 500, imageUrl: '', description: '風を操る自由な精霊使いのアバター', owned: false },
  { id: 'avatar-puppeteer', name: '人形師', category: 'avatar', price: 650, imageUrl: '', description: '魔法の糸で人形を操る人形師のアバター', owned: false },
  { id: 'avatar-archer', name: '弓使い', category: 'avatar', price: 500, imageUrl: '', description: '森のエルフ風弓使いのアバター', owned: false },
  { id: 'avatar-alchemist', name: '錬金術師', category: 'avatar', price: 550, imageUrl: '', description: '薬品と発明の錬金術師のアバター', owned: false },
  { id: 'avatar-hunter', name: '狩人', category: 'avatar', price: 550, imageUrl: '', description: '森を駆ける罠と弓の使い手のアバター', owned: false },
  { id: 'avatar-navigator', name: '操舵士', category: 'avatar', price: 600, imageUrl: '', description: '空飛ぶ船を操る操舵士のアバター', owned: false },
  // --- 冒険・バトル系（中学年向け） ---
  { id: 'avatar-astrologer', name: '星術師', category: 'avatar', price: 550, imageUrl: '', description: '星と月の力を読み解く星術師のアバター', owned: false },
  { id: 'avatar-astronomer', name: '天文学者', category: 'avatar', price: 600, imageUrl: '', description: '星と宇宙の神秘を読み解く天文学者のアバター', owned: false },
  { id: 'avatar-clockmaker', name: '時計師', category: 'avatar', price: 600, imageUrl: '', description: '時間の魔法を操る神秘の時計師のアバター', owned: false },
  { id: 'avatar-ice-mage', name: '氷の魔法使い', category: 'avatar', price: 700, imageUrl: '', description: '氷の結晶を操る魔法使いのアバター', owned: false },
  { id: 'avatar-knight', name: '騎士', category: 'avatar', price: 650, imageUrl: '', description: '聖剣を掲げる騎士のアバター', owned: false },
  { id: 'avatar-star-knight', name: '星の騎士', category: 'avatar', price: 700, imageUrl: '', description: '星の力を纏う天空の騎士のアバター', owned: false },
  { id: 'avatar-dragon-rider-girl', name: '竜騎士', category: 'avatar', price: 600, imageUrl: '', description: '竜と共に空を駆ける少女のアバター', owned: false },
  { id: 'avatar-pirate-prince', name: '海賊王子', category: 'avatar', price: 650, imageUrl: '', description: '海を支配する若き海賊王子のアバター', owned: false },
  { id: 'avatar-stonemason', name: '石工', category: 'avatar', price: 550, imageUrl: '', description: '岩と大地の魔法を操る石工のアバター', owned: false },
  { id: 'avatar-blacksmith', name: '鍛冶師', category: 'avatar', price: 500, imageUrl: '', description: '伝説の武器を鋳造する鍛冶師のアバター', owned: false },
  // --- クール・カッコいい系（中高学年向け） ---
  { id: 'avatar-flame-dancer', name: '炎の舞姫', category: 'avatar', price: 700, imageUrl: '', description: '炎をまとい舞う情熱の舞姫のアバター', owned: false },
  { id: 'avatar-thunder-warrior', name: '雷の戦士', category: 'avatar', price: 600, imageUrl: '', description: '雷をまとう電撃の戦士のアバター', owned: false },
  { id: 'avatar-werewolf', name: '狼男', category: 'avatar', price: 600, imageUrl: '', description: '月夜に力を増す狼戦士のアバター', owned: false },
  { id: 'avatar-beastman', name: '獣人', category: 'avatar', price: 600, imageUrl: '', description: '虎の力を持つ格闘家のアバター', owned: false },
  { id: 'avatar-desert-traveler', name: '砂漠の旅人', category: 'avatar', price: 550, imageUrl: '', description: '砂漠を渡る孤高の旅人のアバター', owned: false },
  { id: 'avatar-dark-swordsman', name: '魔剣士', category: 'avatar', price: 600, imageUrl: '', description: '魔力を帯びた剣を操る魔剣士のアバター', owned: false },
  { id: 'avatar-sage', name: '賢者', category: 'avatar', price: 700, imageUrl: '', description: '古の知識を操る賢者のアバター', owned: false },
  // --- ダーク・ミステリアス系（高学年向け） ---
  { id: 'avatar-vampire-girl', name: '吸血鬼', category: 'avatar', price: 650, imageUrl: '', description: '夜を支配する美しき吸血鬼のアバター', owned: false },
  { id: 'avatar-assassin', name: '暗殺者', category: 'avatar', price: 650, imageUrl: '', description: '闇に潜む二刀流の暗殺者のアバター', owned: false },
  { id: 'avatar-shadow-mage', name: '影の魔導士', category: 'avatar', price: 700, imageUrl: '', description: '闇の魔法を操る神秘の魔導士のアバター', owned: false },
  { id: 'avatar-demon-king', name: '魔王', category: 'avatar', price: 700, imageUrl: '', description: '闇のオーラをまとう魔王のアバター', owned: false },
  { id: 'title-explorer', name: '冒険王', category: 'title', price: 300, imageUrl: '', description: '称号: 冒険王', owned: false },
  { id: 'title-scholar', name: '知識の探究者', category: 'title', price: 300, imageUrl: '', description: '称号: 知識の探究者', owned: true },
  { id: 'title-legend', name: '伝説のクエスター', category: 'title', price: 1000, imageUrl: '', description: '称号: 伝説のクエスター', owned: false },
];
