import type { User, GameDefinition, GachaCard, RankingEntry, ShopItem } from './types';

export const MOCK_USER: User = {
  id: 'user-001',
  nickname: 'さとる',
  classId: 'basic',
  avatarUrl: '',
  avatarType: 'boy',
  equippedAvatarId: null,
  purchasedAvatarIds: [],
  titleId: 'beginner',
  level: 5,
  totalAlt: 1240,
  currentAlt: 1240,
  streakDays: 7,
  lastLogin: new Date().toISOString(),
  createdAt: '2025-01-01T00:00:00Z',
};

export const MOCK_GAMES: GameDefinition[] = [
  {
    id: 'number-tap',
    title: '数字タップゲーム',
    description: '画面に表示される数字を順番にタップしよう！',
    category: 'math',
    difficulty: 1,
    thumbnail: '',
    altReward: 10,
    estimatedMinutes: 2,
    emoji: '🔢',
  },
  {
    id: 'fraction-fusion',
    title: '分数フュージョン',
    description: '分数を合わせて目標の数を作ろう！',
    category: 'math',
    difficulty: 3,
    thumbnail: '',
    altReward: 15,
    estimatedMinutes: 3,
    emoji: '➗',
  },
  {
    id: 'japan-map-quiz',
    title: '日本地図クイズ',
    description: '都道府県の位置を当てよう！',
    category: 'social',
    difficulty: 2,
    thumbnail: '',
    altReward: 10,
    estimatedMinutes: 3,
    emoji: '🗾',
  },
  {
    id: 'math-battle',
    title: '算数バトル',
    description: '計算問題を素早く解いてスコアを稼ごう！',
    category: 'puzzle',
    difficulty: 2,
    thumbnail: '',
    altReward: 10,
    estimatedMinutes: 2,
    emoji: '⚔️',
  },
  {
    id: 'kotowaza-drop',
    title: 'ことわざドロップ',
    description: 'ことわざの穴埋めに挑戦！',
    category: 'japanese',
    difficulty: 2,
    thumbnail: '',
    altReward: 10,
    estimatedMinutes: 3,
    emoji: '📝',
  },
  {
    id: 'history-karuta',
    title: '歴史カルタ',
    description: '歴史上の人物や出来事をカルタで学ぼう！',
    category: 'social',
    difficulty: 3,
    thumbnail: '',
    altReward: 15,
    estimatedMinutes: 5,
    emoji: '🏯',
  },
  {
    id: 'science-team',
    title: '編成チーム',
    description: '科学者チームを編成してミッションに挑もう！',
    category: 'science',
    difficulty: 3,
    thumbnail: '',
    altReward: 20,
    estimatedMinutes: 5,
    emoji: '🔬',
  },
  {
    id: 'inquiry-quest',
    title: '探究クエスト',
    description: '不思議な謎を解き明かそう！',
    category: 'inquiry',
    difficulty: 4,
    thumbnail: '',
    altReward: 25,
    estimatedMinutes: 10,
    emoji: '💡',
  },
];

export const MOCK_CARDS: GachaCard[] = [
  { id: 'c001', name: '織田信長', category: 'great_person', rarity: 5, description: '戦国時代の革命児。天下統一を目指した武将。', imageUrl: '', era: '1534-1582' },
  { id: 'c002', name: 'マリー・キュリー', category: 'great_person', rarity: 4, description: '放射能の研究でノーベル賞を2度受賞した科学者。', imageUrl: '', era: '1867-1934' },
  { id: 'c003', name: 'カブトムシ', category: 'creature', rarity: 1, description: '日本の夏の定番。角が自慢の甲虫。', imageUrl: '' },
  { id: 'c004', name: 'クジラ', category: 'creature', rarity: 3, description: '地球最大の哺乳類。海の王者。', imageUrl: '' },
  { id: 'c005', name: '万里の長城', category: 'heritage', rarity: 4, description: '中国の巨大な防壁。世界遺産。', imageUrl: '' },
  { id: 'c006', name: 'コロッセオ', category: 'heritage', rarity: 3, description: '古代ローマの円形闘技場。', imageUrl: '' },
  { id: 'c007', name: '電球', category: 'invention', rarity: 2, description: 'エジソンが実用化した照明器具。', imageUrl: '' },
  { id: 'c008', name: 'インターネット', category: 'invention', rarity: 5, description: '世界を変えた情報通信技術。', imageUrl: '' },
  { id: 'c009', name: 'クエスくん', category: 'trail', rarity: 6, description: 'TRAIL QUEST WORLDの伝説のマスコット！', imageUrl: '' },
  { id: 'c010', name: 'タンQちゃん', category: 'trail', rarity: 2, description: '探究心あふれるかわいいキャラクター。', imageUrl: '' },
  { id: 'c011', name: 'レオナルド・ダ・ヴィンチ', category: 'great_person', rarity: 6, description: '万能の天才。芸術家にして科学者。', imageUrl: '', era: '1452-1519' },
  { id: 'c012', name: '徳川家康', category: 'great_person', rarity: 4, description: '江戸幕府を開いた征夷大将軍。', imageUrl: '', era: '1543-1616' },
  { id: 'c013', name: 'アインシュタイン', category: 'great_person', rarity: 5, description: '相対性理論を発表した天才物理学者。', imageUrl: '', era: '1879-1955' },
  { id: 'c014', name: 'ドラゴン', category: 'creature', rarity: 5, description: '伝説の火を吐く竜。', imageUrl: '' },
  { id: 'c015', name: 'ユニコーン', category: 'creature', rarity: 3, description: '一角獣。純粋さの象徴。', imageUrl: '' },
  { id: 'c016', name: 'ピラミッド', category: 'heritage', rarity: 3, description: 'エジプトの巨大建造物。', imageUrl: '' },
  { id: 'c017', name: '活版印刷', category: 'invention', rarity: 2, description: 'グーテンベルクが発明した印刷技術。', imageUrl: '' },
  { id: 'c018', name: '蒸気機関', category: 'invention', rarity: 3, description: '産業革命を起こした動力源。', imageUrl: '' },
  { id: 'c019', name: 'フェニックス', category: 'creature', rarity: 4, description: '不死鳥。炎から蘇る伝説の鳥。', imageUrl: '' },
  { id: 'c020', name: '九尾の狐', category: 'creature', rarity: 5, description: '九本の尻尾を持つ妖狐。', imageUrl: '' },
];

// Daily Missions
export const MOCK_DAILY_MISSIONS = [
  { id: 'mission-001', title: 'ゲームを3回クリア', description: 'ゲームを3回クリアしよう', reward: 15, category: 'game', progress: 1, target: 3 },
  { id: 'mission-002', title: 'ガチャを1回引く', description: 'ノーマルガチャを1回引こう', reward: 10, category: 'gacha', progress: 0, target: 1 },
  { id: 'mission-003', title: 'カードをコレクションで確認', description: 'コレクション画面でカードを確認しよう', reward: 5, category: 'collection', progress: 0, target: 1 },
  { id: 'mission-004', title: 'プレミアムガチャを1回引く', description: 'プレミアムガチャに挑戦しよう', reward: 20, category: 'gacha', progress: 0, target: 1 },
  { id: 'mission-005', title: 'SR以上を引く', description: 'SR以上のレアカードを引こう', reward: 30, category: 'gacha', progress: 0, target: 1 },
];

export const MOCK_RANKINGS: RankingEntry[] = [
  { rank: 1, userId: 'u1', nickname: 'いけだ', avatarUrl: '', score: 520, level: 8 },
  { rank: 2, userId: 'u2', nickname: 'あおら', avatarUrl: '', score: 380, level: 6 },
  { rank: 3, userId: 'u3', nickname: 'たかぎ', avatarUrl: '', score: 210, level: 5 },
  { rank: 4, userId: 'u4', nickname: 'みやもと', avatarUrl: '', score: 170, level: 4 },
  { rank: 5, userId: 'u5', nickname: 'やまだ', avatarUrl: '', score: 150, level: 4 },
  { rank: 6, userId: 'u6', nickname: 'すずき', avatarUrl: '', score: 130, level: 3 },
  { rank: 7, userId: 'u7', nickname: 'たなか', avatarUrl: '', score: 110, level: 3 },
  { rank: 8, userId: 'u8', nickname: 'さとう', avatarUrl: '', score: 90, level: 2 },
  { rank: 9, userId: 'u9', nickname: 'わたなべ', avatarUrl: '', score: 70, level: 2 },
  { rank: 10, userId: 'u10', nickname: 'いとう', avatarUrl: '', score: 50, level: 1 },
];

export const MOCK_SHOP_ITEMS: ShopItem[] = [
  { id: 'avatar-samurai', name: '侍', category: 'avatar', price: 500, imageUrl: '', description: '勇敢な侍のアバター', owned: false },
  { id: 'avatar-witch', name: '魔女', category: 'avatar', price: 500, imageUrl: '', description: '賢い魔女のアバター', owned: false },
  { id: 'avatar-pirate', name: '海賊', category: 'avatar', price: 600, imageUrl: '', description: '冒険好きな海賊のアバター', owned: false },
  { id: 'avatar-angel', name: '天使', category: 'avatar', price: 450, imageUrl: '', description: '優しい天使のアバター', owned: false },
  { id: 'avatar-dragon-knight', name: 'ドラゴンナイト', category: 'avatar', price: 800, imageUrl: '', description: 'ドラゴンに乗る勇者', owned: false },
  { id: 'avatar-ninja', name: '忍者', category: 'avatar', price: 550, imageUrl: '', description: '素早い忍者のアバター', owned: false },
  { id: 'avatar-scientist', name: '科学者', category: 'avatar', price: 400, imageUrl: '', description: '知識豊かな科学者のアバター', owned: false },
  { id: 'avatar-princess', name: '姫', category: 'avatar', price: 700, imageUrl: '', description: '優雅な姫のアバター', owned: false },
  { id: 'avatar-ninja-chibi', name: '忍者', category: 'avatar', price: 550, imageUrl: '', description: '影に潜む忍のアバター', owned: false },
  { id: 'avatar-princess-chibi', name: '姫', category: 'avatar', price: 700, imageUrl: '', description: '優雅な姫のアバター', owned: false },
  { id: 'avatar-witch-chibi', name: '魔女', category: 'avatar', price: 500, imageUrl: '', description: '賢い魔女のアバター', owned: false },
  { id: 'avatar-angel-chibi', name: '天使', category: 'avatar', price: 450, imageUrl: '', description: '優しい天使のアバター', owned: false },
  { id: 'title-explorer', name: '冒険王', category: 'title', price: 300, imageUrl: '', description: '称号: 冒険王', owned: false },
  { id: 'title-scholar', name: '知識の探究者', category: 'title', price: 300, imageUrl: '', description: '称号: 知識の探究者', owned: true },
  { id: 'title-legend', name: '伝説のクエスター', category: 'title', price: 1000, imageUrl: '', description: '称号: 伝説のクエスター', owned: false },
];
