/**
 * Quest Quiz Data - デッキ別クエストクイズ
 * 学習カードに連動: ビギナー=タイトル、チャレンジャー=本文、マスター=豆知識、レジェンド=応用
 * ruby タグでふりがな対応（beginner/challengerは厚め、master/legendは通常レベル）
 */
import type { DeckKey, QuestDifficulty } from './questProgress';

export interface QuestQuiz {
  question: string;
  choices: string[];
  correctIndex: number;
}

type QuizDataMap = Record<DeckKey, Record<QuestDifficulty, QuestQuiz[]>> & {
  nobunaga?: Record<QuestDifficulty, QuestQuiz[]>;
  wolf?: Record<QuestDifficulty, QuestQuiz[]>;
};

export const QUEST_QUIZ_DATA: QuizDataMap = {

  // ================================================================
  // ⚔️ ナポレオン
  // ================================================================
  napoleon: {
    beginner: [
      { question: 'ナポレオンはどこの<ruby>国<rt>くに</rt></ruby>の<ruby>人<rt>ひと</rt></ruby>？', choices: ['フランス', 'イギリス', 'ドイツ', 'イタリア'], correctIndex: 0 },
      { question: 'フランス<ruby>革命<rt>かくめい</rt></ruby>で<ruby>国民<rt>こくみん</rt></ruby>が<ruby>襲<rt>おそ</rt></ruby>った<ruby>場所<rt>ばしょ</rt></ruby>は？', choices: ['バスティーユ<ruby>牢獄<rt>ろうごく</rt></ruby>', 'ベルサイユ<ruby>宮殿<rt>きゅうでん</rt></ruby>', 'ノートルダム<ruby>大聖堂<rt>だいせいどう</rt></ruby>', 'エッフェル<ruby>塔<rt>とう</rt></ruby>'], correctIndex: 0 },
      { question: 'ナポレオンが<ruby>最後<rt>さいご</rt></ruby>に<ruby>負<rt>ま</rt></ruby>けた<ruby>戦<rt>たたか</rt></ruby>いの<ruby>名前<rt>なまえ</rt></ruby>は？', choices: ['ワーテルローの<ruby>戦<rt>たたか</rt></ruby>い', 'トラファルガーの<ruby>海戦<rt>かいせん</rt></ruby>', 'アウステルリッツの<ruby>戦<rt>たたか</rt></ruby>い', 'ライプツィヒの<ruby>戦<rt>たたか</rt></ruby>い'], correctIndex: 0 },
      { question: 'ナポレオンが<ruby>作<rt>つく</rt></ruby>った<ruby>有名<rt>ゆうめい</rt></ruby>な<ruby>法律<rt>ほうりつ</rt></ruby>の<ruby>名前<rt>なまえ</rt></ruby>は？', choices: ['ナポレオン<ruby>法典<rt>ほうてん</rt></ruby>', '<ruby>大憲章<rt>だいけんしょう</rt></ruby>', '<ruby>権利<rt>けんり</rt></ruby>の<ruby>章典<rt>しょうてん</rt></ruby>', '<ruby>十二表法<rt>じゅうにひょうほう</rt></ruby>'], correctIndex: 0 },
      { question: 'ナポレオンは<ruby>何<rt>なに</rt></ruby>になった？', choices: ['<ruby>皇帝<rt>こうてい</rt></ruby>', '<ruby>王<rt>おう</rt></ruby>', '<ruby>大統領<rt>だいとうりょう</rt></ruby>', '<ruby>将軍<rt>しょうぐん</rt></ruby>'], correctIndex: 0 },
    ],
    challenger: [
      { question: 'ナポレオンが<ruby>生<rt>う</rt></ruby>まれた<ruby>島<rt>しま</rt></ruby>はどこ？', choices: ['<ruby>地中海<rt>ちちゅうかい</rt></ruby>の<ruby>小<rt>ちい</rt></ruby>さな<ruby>島<rt>しま</rt></ruby>', 'イギリスの<ruby>島<rt>しま</rt></ruby>', 'カリブ<ruby>海<rt>かい</rt></ruby>の<ruby>島<rt>しま</rt></ruby>', '<ruby>北海<rt>ほっかい</rt></ruby>の<ruby>島<rt>しま</rt></ruby>'], correctIndex: 0 },
      { question: 'フランス<ruby>革命<rt>かくめい</rt></ruby>のスローガンは？', choices: ['<ruby>自由<rt>じゆう</rt></ruby>・<ruby>平等<rt>びょうどう</rt></ruby>・<ruby>友愛<rt>ゆうあい</rt></ruby>', '<ruby>正義<rt>せいぎ</rt></ruby>・<ruby>秩序<rt>ちつじょ</rt></ruby>・<ruby>平和<rt>へいわ</rt></ruby>', '<ruby>信仰<rt>しんこう</rt></ruby>・<ruby>希望<rt>きぼう</rt></ruby>・<ruby>愛<rt>あい</rt></ruby>', '<ruby>勇気<rt>ゆうき</rt></ruby>・<ruby>名誉<rt>めいよ</rt></ruby>・<ruby>忠誠<rt>ちゅうせい</rt></ruby>'], correctIndex: 0 },
      { question: 'ナポレオンの<ruby>戴冠式<rt>たいかんしき</rt></ruby>で<ruby>特別<rt>とくべつ</rt></ruby>だったことは？', choices: ['<ruby>自分<rt>じぶん</rt></ruby>で<ruby>王冠<rt>おうかん</rt></ruby>を<ruby>被<rt>かぶ</rt></ruby>った', '<ruby>教皇<rt>きょうこう</rt></ruby>が<ruby>王冠<rt>おうかん</rt></ruby>を<ruby>被<rt>かぶ</rt></ruby>せた', '<ruby>国民<rt>こくみん</rt></ruby>が<ruby>投票<rt>とうひょう</rt></ruby>で<ruby>決<rt>き</rt></ruby>めた', '<ruby>戦<rt>たたか</rt></ruby>いで<ruby>勝<rt>か</rt></ruby>ち<ruby>取<rt>と</rt></ruby>った'], correctIndex: 0 },
      { question: 'ワーテルローで<ruby>負<rt>ま</rt></ruby>けた<ruby>後<rt>あと</rt></ruby>、ナポレオンはどうなった？', choices: ['<ruby>島<rt>しま</rt></ruby>に<ruby>追放<rt>ついほう</rt></ruby>された', '<ruby>処刑<rt>しょけい</rt></ruby>された', '<ruby>引退<rt>いんたい</rt></ruby>した', '<ruby>別<rt>べつ</rt></ruby>の<ruby>国<rt>くに</rt></ruby>の<ruby>王<rt>おう</rt></ruby>になった'], correctIndex: 0 },
      { question: 'ナポレオン<ruby>法典<rt>ほうてん</rt></ruby>の<ruby>一番<rt>いちばん</rt></ruby><ruby>大事<rt>だいじ</rt></ruby>な<ruby>考<rt>かんが</rt></ruby>えは？', choices: ['<ruby>法<rt>ほう</rt></ruby>の<ruby>前<rt>まえ</rt></ruby>に<ruby>全員<rt>ぜんいん</rt></ruby><ruby>平等<rt>びょうどう</rt></ruby>', '<ruby>王様<rt>おうさま</rt></ruby>が<ruby>一番<rt>いちばん</rt></ruby><ruby>偉<rt>えら</rt></ruby>い', 'お<ruby>金持<rt>かねも</rt></ruby>ちが<ruby>優先<rt>ゆうせん</rt></ruby>', '<ruby>軍人<rt>ぐんじん</rt></ruby>が<ruby>国<rt>くに</rt></ruby>を<ruby>治<rt>おさ</rt></ruby>める'], correctIndex: 0 },
    ],
    master: [
      { question: 'ナポレオンの「チビ」のイメージを<ruby>広<rt>ひろ</rt></ruby>めたのは？', choices: ['イギリス', 'フランス<ruby>国民<rt>こくみん</rt></ruby>', 'ロシア', 'プロイセン'], correctIndex: 0 },
      { question: 'バスティーユ<ruby>襲撃日<rt>しゅうげきび</rt></ruby>は<ruby>今<rt>いま</rt></ruby><ruby>何<rt>なん</rt></ruby>の<ruby>日<rt>ひ</rt></ruby>？', choices: ['フランスの<ruby>建国記念日<rt>けんこくきねんび</rt></ruby>', 'クリスマス', '<ruby>革命<rt>かくめい</rt></ruby><ruby>記念日<rt>きねんび</rt></ruby>', '<ruby>独立<rt>どくりつ</rt></ruby><ruby>記念日<rt>きねんび</rt></ruby>'], correctIndex: 0 },
      { question: 'ナポレオンが<ruby>自分<rt>じぶん</rt></ruby>で<ruby>王冠<rt>おうかん</rt></ruby>を<ruby>被<rt>かぶ</rt></ruby>った<ruby>意味<rt>いみ</rt></ruby>は？', choices: ['<ruby>誰<rt>だれ</rt></ruby>の<ruby>力<rt>ちから</rt></ruby>でもなく<ruby>自分<rt>じぶん</rt></ruby>の<ruby>力<rt>ちから</rt></ruby>で<ruby>皇帝<rt>こうてい</rt></ruby>になった', '<ruby>教皇<rt>きょうこう</rt></ruby>に<ruby>失礼<rt>しつれい</rt></ruby>だった', '<ruby>伝統<rt>でんとう</rt></ruby>を<ruby>守<rt>まも</rt></ruby>った', '<ruby>時間<rt>じかん</rt></ruby>がなかった'], correctIndex: 0 },
      { question: 'ワーテルローの<ruby>戦場<rt>せんじょう</rt></ruby>は<ruby>今<rt>いま</rt></ruby>どこの<ruby>国<rt>くに</rt></ruby>にある？', choices: ['ベルギー', 'フランス', 'ドイツ', 'オランダ'], correctIndex: 0 },
      { question: 'ナポレオン<ruby>法典<rt>ほうてん</rt></ruby>の<ruby>影響<rt>えいきょう</rt></ruby>を<ruby>受<rt>う</rt></ruby>けた<ruby>意外<rt>いがい</rt></ruby>な<ruby>国<rt>くに</rt></ruby>は？', choices: ['<ruby>日本<rt>にほん</rt></ruby>', '<ruby>中国<rt>ちゅうごく</rt></ruby>', 'インド', 'ロシア'], correctIndex: 0 },
    ],
    legend: [
      { question: 'ナポレオンが<ruby>皇帝<rt>こうてい</rt></ruby>になれた<ruby>最大<rt>さいだい</rt></ruby>の<ruby>理由<rt>りゆう</rt></ruby>は？', choices: ['<ruby>革命後<rt>かくめいご</rt></ruby>の<ruby>混乱<rt>こんらん</rt></ruby>をまとめた', 'お<ruby>金持<rt>かねも</rt></ruby>ちだった', '<ruby>王族<rt>おうぞく</rt></ruby>だった', '<ruby>外国<rt>がいこく</rt></ruby>の<ruby>支援<rt>しえん</rt></ruby>を<ruby>受<rt>う</rt></ruby>けた'], correctIndex: 0 },
      { question: 'フランス<ruby>革命<rt>かくめい</rt></ruby>が<ruby>起<rt>お</rt></ruby>きた<ruby>根本的<rt>こんぽんてき</rt></ruby>な<ruby>原因<rt>げんいん</rt></ruby>は？', choices: ['<ruby>国民<rt>こくみん</rt></ruby>の<ruby>貧困<rt>ひんこん</rt></ruby>と<ruby>不満<rt>ふまん</rt></ruby>', '<ruby>外国<rt>がいこく</rt></ruby>の<ruby>侵攻<rt>しんこう</rt></ruby>', '<ruby>王<rt>おう</rt></ruby>の<ruby>急死<rt>きゅうし</rt></ruby>', '<ruby>宗教<rt>しゅうきょう</rt></ruby>の<ruby>対立<rt>たいりつ</rt></ruby>'], correctIndex: 0 },
      { question: 'ナポレオン<ruby>法典<rt>ほうてん</rt></ruby>が「<ruby>戦争<rt>せんそう</rt></ruby>の<ruby>勝利<rt>しょうり</rt></ruby>より<ruby>大<rt>おお</rt></ruby>きな<ruby>遺産<rt>いさん</rt></ruby>」と<ruby>言<rt>い</rt></ruby>われる<ruby>理由<rt>りゆう</rt></ruby>は？', choices: ['<ruby>世界中<rt>せかいじゅう</rt></ruby>の<ruby>法律<rt>ほうりつ</rt></ruby>の<ruby>基礎<rt>きそ</rt></ruby>になったから', 'たくさんの<ruby>国<rt>くに</rt></ruby>を<ruby>征服<rt>せいふく</rt></ruby>したから', '<ruby>経済<rt>けいざい</rt></ruby>を<ruby>発展<rt>はってん</rt></ruby>させたから', '<ruby>軍隊<rt>ぐんたい</rt></ruby>を<ruby>強<rt>つよ</rt></ruby>くしたから'], correctIndex: 0 },
      { question: 'もしナポレオンがワーテルローで<ruby>勝<rt>か</rt></ruby>っていたら？', choices: ['ヨーロッパの<ruby>支配<rt>しはい</rt></ruby>が<ruby>続<rt>つづ</rt></ruby>いた<ruby>可能性<rt>かのうせい</rt></ruby>', '<ruby>何<rt>なに</rt></ruby>も<ruby>変<rt>か</rt></ruby>わらなかった', 'すぐに<ruby>引退<rt>いんたい</rt></ruby>した', '<ruby>平和<rt>へいわ</rt></ruby>になった'], correctIndex: 0 },
      { question: 'ナポレオンの<ruby>実際<rt>じっさい</rt></ruby>の<ruby>身長<rt>しんちょう</rt></ruby>168cmは<ruby>当時<rt>とうじ</rt></ruby>としてどうだった？', choices: ['<ruby>平均的<rt>へいきんてき</rt></ruby>', 'とても<ruby>低<rt>ひく</rt></ruby>い', 'とても<ruby>高<rt>たか</rt></ruby>い', 'わからない'], correctIndex: 0 },
    ],
  },

  // ================================================================
  // 🌿 アマゾン
  // ================================================================
  amazon: {
    beginner: [
      { question: 'アマゾン<ruby>川<rt>がわ</rt></ruby>は<ruby>世界一<rt>せかいいち</rt></ruby><ruby>何<rt>なに</rt></ruby>が<ruby>多<rt>おお</rt></ruby>い<ruby>川<rt>かわ</rt></ruby>？', choices: ['<ruby>水<rt>みず</rt></ruby>の<ruby>量<rt>りょう</rt></ruby>', '<ruby>長<rt>なが</rt></ruby>さ', '<ruby>深<rt>ふか</rt></ruby>さ', '<ruby>魚<rt>さかな</rt></ruby>の<ruby>数<rt>かず</rt></ruby>'], correctIndex: 0 },
      { question: 'ピラニアは<ruby>本当<rt>ほんとう</rt></ruby>はどんな<ruby>性格<rt>せいかく</rt></ruby>？', choices: ['<ruby>臆病<rt>おくびょう</rt></ruby>', '<ruby>凶暴<rt>きょうぼう</rt></ruby>', 'のんびり', '<ruby>賢<rt>かしこ</rt></ruby>い'], correctIndex: 0 },
      { question: '<ruby>熱帯雨林<rt>ねったいうりん</rt></ruby>の<ruby>別名<rt>べつめい</rt></ruby>は？', choices: ['<ruby>地球<rt>ちきゅう</rt></ruby>の<ruby>肺<rt>はい</rt></ruby>', '<ruby>地球<rt>ちきゅう</rt></ruby>の<ruby>心臓<rt>しんぞう</rt></ruby>', '<ruby>地球<rt>ちきゅう</rt></ruby>の<ruby>目<rt>め</rt></ruby>', '<ruby>地球<rt>ちきゅう</rt></ruby>の<ruby>手<rt>て</rt></ruby>'], correctIndex: 0 },
      { question: 'トゥカノ<ruby>族<rt>ぞく</rt></ruby>が<ruby>大切<rt>たいせつ</rt></ruby>にしている<ruby>動物<rt>どうぶつ</rt></ruby>は？', choices: ['アナコンダ', 'ジャガー', 'ワシ', 'カメ'], correctIndex: 0 },
      { question: '<ruby>毒矢<rt>どくや</rt></ruby>カエルの<ruby>鮮<rt>あざ</rt></ruby>やかな<ruby>色<rt>いろ</rt></ruby>の<ruby>意味<rt>いみ</rt></ruby>は？', choices: ['<ruby>危険<rt>きけん</rt></ruby>の<ruby>警告<rt>けいこく</rt></ruby>', '<ruby>仲間<rt>なかま</rt></ruby>への<ruby>合図<rt>あいず</rt></ruby>', 'えさを<ruby>集<rt>あつ</rt></ruby>めるため', 'かくれるため'], correctIndex: 0 },
    ],
    challenger: [
      { question: 'アマゾン<ruby>川<rt>がわ</rt></ruby>の<ruby>長<rt>なが</rt></ruby>さはどのくらい？', choices: ['<ruby>約<rt>やく</rt></ruby>6,400km', '<ruby>約<rt>やく</rt></ruby>3,000km', '<ruby>約<rt>やく</rt></ruby>10,000km', '<ruby>約<rt>やく</rt></ruby>1,500km'], correctIndex: 0 },
      { question: 'ピラニアが<ruby>川<rt>かわ</rt></ruby>で<ruby>果<rt>は</rt></ruby>たしている<ruby>役割<rt>やくわり</rt></ruby>は？', choices: ['<ruby>川<rt>かわ</rt></ruby>の<ruby>掃除屋<rt>そうじや</rt></ruby>', '<ruby>最強<rt>さいきょう</rt></ruby>の<ruby>捕食者<rt>ほしょくしゃ</rt></ruby>', '<ruby>川<rt>かわ</rt></ruby>の<ruby>見張<rt>みは</rt></ruby>り', '<ruby>何<rt>なに</rt></ruby>もしていない'], correctIndex: 0 },
      { question: '<ruby>熱帯雨林<rt>ねったいうりん</rt></ruby>は<ruby>地球<rt>ちきゅう</rt></ruby>の<ruby>酸素<rt>さんそ</rt></ruby>の<ruby>何<rt>なん</rt></ruby>%を<ruby>作<rt>つく</rt></ruby>っている？', choices: ['<ruby>約<rt>やく</rt></ruby>20%', '<ruby>約<rt>やく</rt></ruby>5%', '<ruby>約<rt>やく</rt></ruby>50%', '<ruby>約<rt>やく</rt></ruby>80%'], correctIndex: 0 },
      { question: 'トゥカノ<ruby>族<rt>ぞく</rt></ruby>の<ruby>神話<rt>しんわ</rt></ruby>でアナコンダは<ruby>何<rt>なに</rt></ruby>をした？', choices: ['<ruby>川<rt>かわ</rt></ruby>を<ruby>旅<rt>たび</rt></ruby>して<ruby>村<rt>むら</rt></ruby>を<ruby>作<rt>つく</rt></ruby>った', '<ruby>空<rt>そら</rt></ruby>を<ruby>飛<rt>と</rt></ruby>んだ', '<ruby>山<rt>やま</rt></ruby>を<ruby>作<rt>つく</rt></ruby>った', '<ruby>海<rt>うみ</rt></ruby>を<ruby>作<rt>つく</rt></ruby>った'], correctIndex: 0 },
      { question: '<ruby>先住民<rt>せんじゅうみん</rt></ruby>は<ruby>毒矢<rt>どくや</rt></ruby>カエルの<ruby>毒<rt>どく</rt></ruby>を<ruby>何<rt>なに</rt></ruby>に<ruby>使<rt>つか</rt></ruby>った？', choices: ['<ruby>狩<rt>か</rt></ruby>りの<ruby>矢<rt>や</rt></ruby>', '<ruby>薬<rt>くすり</rt></ruby>', '<ruby>食<rt>た</rt></ruby>べ<ruby>物<rt>もの</rt></ruby>', 'お<ruby>祭<rt>まつ</rt></ruby>り'], correctIndex: 0 },
    ],
    master: [
      { question: 'アマゾン<ruby>川<rt>がわ</rt></ruby>の<ruby>河口<rt>かこう</rt></ruby>の<ruby>幅<rt>はば</rt></ruby>はどのくらい？', choices: ['<ruby>約<rt>やく</rt></ruby>330km', '<ruby>約<rt>やく</rt></ruby>30km', '<ruby>約<rt>やく</rt></ruby>1,000km', '<ruby>約<rt>やく</rt></ruby>100km'], correctIndex: 0 },
      { question: 'アマゾンの<ruby>地元<rt>じもと</rt></ruby>の<ruby>子<rt>こ</rt></ruby>どもはピラニアがいる<ruby>川<rt>かわ</rt></ruby>でどうしている？', choices: ['<ruby>普通<rt>ふつう</rt></ruby>に<ruby>泳<rt>およ</rt></ruby>いでいる', '<ruby>絶対<rt>ぜったい</rt></ruby>に<ruby>近<rt>ちか</rt></ruby>づかない', '<ruby>毎日<rt>まいにち</rt></ruby><ruby>逃<rt>に</rt></ruby>げている', '<ruby>戦<rt>たたか</rt></ruby>っている'], correctIndex: 0 },
      { question: 'アマゾンにまだ<ruby>発見<rt>はっけん</rt></ruby>されていない<ruby>生<rt>い</rt></ruby>き<ruby>物<rt>もの</rt></ruby>はどのくらい？', choices: ['<ruby>数百万種<rt>すうひゃくまんしゅ</rt></ruby>', '<ruby>数十種<rt>すうじっしゅ</rt></ruby>', 'ゼロ', '<ruby>数百種<rt>すうひゃくしゅ</rt></ruby>'], correctIndex: 0 },
      { question: 'アマゾン<ruby>川<rt>がわ</rt></ruby>がくねくね<ruby>蛇行<rt>だこう</rt></ruby>する<ruby>姿<rt>すがた</rt></ruby>は<ruby>何<rt>なに</rt></ruby>に<ruby>似<rt>に</rt></ruby>ている？', choices: ['アナコンダ', 'ピラニア', 'ワニ', 'カメ'], correctIndex: 0 },
      { question: '<ruby>毒矢<rt>どくや</rt></ruby>カエルが<ruby>飼育下<rt>しいくか</rt></ruby>で<ruby>毒<rt>どく</rt></ruby>を<ruby>作<rt>つく</rt></ruby>れなくなる<ruby>理由<rt>りゆう</rt></ruby>は？', choices: ['<ruby>食<rt>た</rt></ruby>べ<ruby>物<rt>もの</rt></ruby>が<ruby>関係<rt>かんけい</rt></ruby>している', '<ruby>水<rt>みず</rt></ruby>が<ruby>違<rt>ちが</rt></ruby>う', '<ruby>温度<rt>おんど</rt></ruby>が<ruby>違<rt>ちが</rt></ruby>う', 'ストレス'], correctIndex: 0 },
    ],
    legend: [
      { question: '<ruby>河口<rt>かこう</rt></ruby>の<ruby>幅<rt>はば</rt></ruby>330kmを<ruby>日本<rt>にほん</rt></ruby>で<ruby>例<rt>たと</rt></ruby>えると？', choices: ['<ruby>東京<rt>とうきょう</rt></ruby>から<ruby>名古屋<rt>なごや</rt></ruby>くらい', '<ruby>東京<rt>とうきょう</rt></ruby>から<ruby>横浜<rt>よこはま</rt></ruby>くらい', '<ruby>東京<rt>とうきょう</rt></ruby>から<ruby>大阪<rt>おおさか</rt></ruby>くらい', '<ruby>北海道<rt>ほっかいどう</rt></ruby>の<ruby>端<rt>はし</rt></ruby>から<ruby>端<rt>はし</rt></ruby>'], correctIndex: 0 },
      { question: 'ピラニアが「<ruby>川<rt>かわ</rt></ruby>の<ruby>掃除屋<rt>そうじや</rt></ruby>」だとすると、いなくなったらどうなる？', choices: ['<ruby>川<rt>かわ</rt></ruby>が<ruby>汚<rt>よご</rt></ruby>れる', '<ruby>何<rt>なに</rt></ruby>も<ruby>変<rt>か</rt></ruby>わらない', '<ruby>川<rt>かわ</rt></ruby>が<ruby>綺麗<rt>きれい</rt></ruby>になる', '<ruby>魚<rt>さかな</rt></ruby>が<ruby>増<rt>ふ</rt></ruby>える'], correctIndex: 0 },
      { question: '<ruby>熱帯雨林<rt>ねったいうりん</rt></ruby>が「<ruby>地球<rt>ちきゅう</rt></ruby>の<ruby>肺<rt>はい</rt></ruby>」と<ruby>呼<rt>よ</rt></ruby>ばれる<ruby>理由<rt>りゆう</rt></ruby>を<ruby>正<rt>ただ</rt></ruby>しく<ruby>説明<rt>せつめい</rt></ruby>すると？', choices: ['<ruby>酸素<rt>さんそ</rt></ruby>を<ruby>作<rt>つく</rt></ruby>り<ruby>雨<rt>あめ</rt></ruby>を<ruby>降<rt>ふ</rt></ruby>らせるから', '<ruby>大<rt>おお</rt></ruby>きいから', '<ruby>緑<rt>みどり</rt></ruby>が<ruby>多<rt>おお</rt></ruby>いから', '<ruby>動物<rt>どうぶつ</rt></ruby>がいるから'], correctIndex: 0 },
      { question: 'トゥカノ<ruby>族<rt>ぞく</rt></ruby>がアナコンダを「<ruby>祖先<rt>そせん</rt></ruby>」とする<ruby>理由<rt>りゆう</rt></ruby>は<ruby>何<rt>なに</rt></ruby>と<ruby>関係<rt>かんけい</rt></ruby>がある？', choices: ['<ruby>川<rt>かわ</rt></ruby>と<ruby>蛇<rt>へび</rt></ruby>の<ruby>形<rt>かたち</rt></ruby>の<ruby>類似<rt>るいじ</rt></ruby>', 'アナコンダの<ruby>大<rt>おお</rt></ruby>きさ', '<ruby>色<rt>いろ</rt></ruby>の<ruby>美<rt>うつく</rt></ruby>しさ', '<ruby>毒<rt>どく</rt></ruby>の<ruby>強<rt>つよ</rt></ruby>さ'], correctIndex: 0 },
      { question: '<ruby>毒矢<rt>どくや</rt></ruby>カエルの<ruby>毒<rt>どく</rt></ruby>1<ruby>匹分<rt>ぴきぶん</rt></ruby>はどのくらい<ruby>強<rt>つよ</rt></ruby>い？', choices: ['<ruby>大人<rt>おとな</rt></ruby>10<ruby>人分<rt>にんぶん</rt></ruby>の<ruby>致死量<rt>ちしりょう</rt></ruby>', '<ruby>大人<rt>おとな</rt></ruby>1<ruby>人分<rt>にんぶん</rt></ruby>', 'ほとんど<ruby>無害<rt>むがい</rt></ruby>', '<ruby>大人<rt>おとな</rt></ruby>100<ruby>人分<rt>にんぶん</rt></ruby>'], correctIndex: 0 },
    ],
  },

  // ================================================================
  // 🏛️ 始皇帝
  // ================================================================
  qinshi: {
    beginner: [
      { question: '<ruby>始皇帝<rt>しこうてい</rt></ruby>が<ruby>統一<rt>とういつ</rt></ruby>した<ruby>国<rt>くに</rt></ruby>は？', choices: ['<ruby>中国<rt>ちゅうごく</rt></ruby>', '<ruby>日本<rt>にほん</rt></ruby>', 'インド', 'ローマ'], correctIndex: 0 },
      { question: '<ruby>始皇帝<rt>しこうてい</rt></ruby>が<ruby>何歳<rt>なんさい</rt></ruby>で<ruby>王<rt>おう</rt></ruby>になった？', choices: ['13<ruby>歳<rt>さい</rt></ruby>', '20<ruby>歳<rt>さい</rt></ruby>', '30<ruby>歳<rt>さい</rt></ruby>', '5<ruby>歳<rt>さい</rt></ruby>'], correctIndex: 0 },
      { question: '<ruby>万里<rt>ばんり</rt></ruby>の<ruby>長城<rt>ちょうじょう</rt></ruby>は<ruby>何<rt>なに</rt></ruby>から<ruby>国<rt>くに</rt></ruby>を<ruby>守<rt>まも</rt></ruby>るため？', choices: ['<ruby>北<rt>きた</rt></ruby>の<ruby>遊牧民族<rt>ゆうぼくみんぞく</rt></ruby>', '<ruby>南<rt>みなみ</rt></ruby>の<ruby>海賊<rt>かいぞく</rt></ruby>', '<ruby>東<rt>ひがし</rt></ruby>の<ruby>王国<rt>おうこく</rt></ruby>', '<ruby>西<rt>にし</rt></ruby>の<ruby>商人<rt>しょうにん</rt></ruby>'], correctIndex: 0 },
      { question: '「<ruby>焚書<rt>ふんしょ</rt></ruby>」とは<ruby>何<rt>なに</rt></ruby>をしたこと？', choices: ['<ruby>本<rt>ほん</rt></ruby>を<ruby>燃<rt>も</rt></ruby>やした', '<ruby>家<rt>いえ</rt></ruby>を<ruby>建<rt>た</rt></ruby>てた', '<ruby>城<rt>しろ</rt></ruby>を<ruby>作<rt>つく</rt></ruby>った', '<ruby>戦争<rt>せんそう</rt></ruby>をした'], correctIndex: 0 },
      { question: '<ruby>兵馬俑<rt>へいばよう</rt></ruby>は<ruby>何<rt>なに</rt></ruby>を<ruby>守<rt>まも</rt></ruby>るためのもの？', choices: ['<ruby>始皇帝<rt>しこうてい</rt></ruby>の<ruby>墓<rt>はか</rt></ruby>', '<ruby>城<rt>しろ</rt></ruby>', '<ruby>宝物<rt>たからもの</rt></ruby>', '<ruby>国境<rt>こっきょう</rt></ruby>'], correctIndex: 0 },
    ],
    challenger: [
      { question: '「<ruby>皇帝<rt>こうてい</rt></ruby>」という<ruby>言葉<rt>ことば</rt></ruby>を<ruby>作<rt>つく</rt></ruby>ったのは<ruby>誰<rt>だれ</rt></ruby>？', choices: ['<ruby>始皇帝<rt>しこうてい</rt></ruby>', '<ruby>孔子<rt>こうし</rt></ruby>', '<ruby>劉邦<rt>りゅうほう</rt></ruby>', '<ruby>曹操<rt>そうそう</rt></ruby>'], correctIndex: 0 },
      { question: '<ruby>万里<rt>ばんり</rt></ruby>の<ruby>長城<rt>ちょうじょう</rt></ruby>の<ruby>全長<rt>ぜんちょう</rt></ruby>は<ruby>約<rt>やく</rt></ruby><ruby>何<rt>なん</rt></ruby>km？', choices: ['<ruby>約<rt>やく</rt></ruby>2<ruby>万<rt>まん</rt></ruby>km', '<ruby>約<rt>やく</rt></ruby>5<ruby>千<rt>せん</rt></ruby>km', '<ruby>約<rt>やく</rt></ruby>100km', '<ruby>約<rt>やく</rt></ruby>50<ruby>万<rt>まん</rt></ruby>km'], correctIndex: 0 },
      { question: '<ruby>焚書坑儒<rt>ふんしょこうじゅ</rt></ruby>で<ruby>燃<rt>も</rt></ruby>やさなかった<ruby>本<rt>ほん</rt></ruby>は？', choices: ['<ruby>医学<rt>いがく</rt></ruby>や<ruby>農業<rt>のうぎょう</rt></ruby>の<ruby>本<rt>ほん</rt></ruby>', '<ruby>歴史<rt>れきし</rt></ruby>の<ruby>本<rt>ほん</rt></ruby>', '<ruby>詩<rt>し</rt></ruby>の<ruby>本<rt>ほん</rt></ruby>', '<ruby>全部<rt>ぜんぶ</rt></ruby><ruby>燃<rt>も</rt></ruby>やした'], correctIndex: 0 },
      { question: '<ruby>兵馬俑<rt>へいばよう</rt></ruby>の<ruby>特徴<rt>とくちょう</rt></ruby>で<ruby>驚<rt>おどろ</rt></ruby>くべきことは？', choices: ['<ruby>一体<rt>いったい</rt></ruby><ruby>一体<rt>いったい</rt></ruby><ruby>顔<rt>かお</rt></ruby>が<ruby>違<rt>ちが</rt></ruby>う', '<ruby>全部<rt>ぜんぶ</rt></ruby><ruby>同<rt>おな</rt></ruby>じ<ruby>顔<rt>かお</rt></ruby>', '<ruby>金<rt>きん</rt></ruby>でできている', '<ruby>動<rt>うご</rt></ruby>く'], correctIndex: 0 },
      { question: '<ruby>紙<rt>かみ</rt></ruby>が<ruby>発明<rt>はつめい</rt></ruby>される<ruby>前<rt>まえ</rt></ruby>、<ruby>何<rt>なに</rt></ruby>に<ruby>文字<rt>もじ</rt></ruby>を<ruby>書<rt>か</rt></ruby>いていた？', choices: ['<ruby>竹<rt>たけ</rt></ruby>や<ruby>木<rt>き</rt></ruby>の<ruby>板<rt>いた</rt></ruby>', '<ruby>石<rt>いし</rt></ruby>', '<ruby>布<rt>ぬの</rt></ruby>', '<ruby>皮<rt>かわ</rt></ruby>'], correctIndex: 0 },
    ],
    master: [
      { question: '「<ruby>始皇帝<rt>しこうてい</rt></ruby>」の<ruby>意味<rt>いみ</rt></ruby>は？', choices: ['<ruby>最初<rt>さいしょ</rt></ruby>の<ruby>皇帝<rt>こうてい</rt></ruby>', '<ruby>最強<rt>さいきょう</rt></ruby>の<ruby>皇帝<rt>こうてい</rt></ruby>', '<ruby>永遠<rt>えいえん</rt></ruby>の<ruby>皇帝<rt>こうてい</rt></ruby>', '<ruby>偉大<rt>いだい</rt></ruby>な<ruby>皇帝<rt>こうてい</rt></ruby>'], correctIndex: 0 },
      { question: '<ruby>万里<rt>ばんり</rt></ruby>の<ruby>長城<rt>ちょうじょう</rt></ruby>は<ruby>月<rt>つき</rt></ruby>から<ruby>見<rt>み</rt></ruby>えるって<ruby>本当<rt>ほんとう</rt></ruby>？', choices: ['<ruby>嘘<rt>うそ</rt></ruby>', '<ruby>本当<rt>ほんとう</rt></ruby>', '<ruby>条件<rt>じょうけん</rt></ruby>による', 'まだわからない'], correctIndex: 0 },
      { question: '<ruby>兵馬俑<rt>へいばよう</rt></ruby>が<ruby>発見<rt>はっけん</rt></ruby>された<ruby>年<rt>とし</rt></ruby>は？', choices: ['1974<ruby>年<rt>ねん</rt></ruby>', '1900<ruby>年<rt>ねん</rt></ruby>', '2000<ruby>年<rt>ねん</rt></ruby>', '1800<ruby>年<rt>ねん</rt></ruby>'], correctIndex: 0 },
      { question: '<ruby>兵馬俑<rt>へいばよう</rt></ruby>を<ruby>発見<rt>はっけん</rt></ruby>したのはどんな<ruby>人<rt>ひと</rt></ruby>？', choices: ['<ruby>井戸<rt>いど</rt></ruby>を<ruby>掘<rt>ほ</rt></ruby>っていた<ruby>農民<rt>のうみん</rt></ruby>', '<ruby>考古学者<rt>こうこがくしゃ</rt></ruby>', '<ruby>皇帝<rt>こうてい</rt></ruby>の<ruby>子孫<rt>しそん</rt></ruby>', '<ruby>軍人<rt>ぐんじん</rt></ruby>'], correctIndex: 0 },
      { question: '<ruby>紙<rt>かみ</rt></ruby>の<ruby>発明前<rt>はつめいまえ</rt></ruby>の<ruby>本<rt>ほん</rt></ruby>1<ruby>冊分<rt>さつぶん</rt></ruby>の<ruby>竹簡<rt>ちくかん</rt></ruby>の<ruby>重<rt>おも</rt></ruby>さは？', choices: ['<ruby>馬車<rt>ばしゃ</rt></ruby>1<ruby>台分<rt>だいぶん</rt></ruby>', '<ruby>人<rt>ひと</rt></ruby>1<ruby>人分<rt>にんぶん</rt></ruby>', '<ruby>猫<rt>ねこ</rt></ruby>1<ruby>匹分<rt>ぴきぶん</rt></ruby>', 'りんご1<ruby>個分<rt>こぶん</rt></ruby>'], correctIndex: 0 },
    ],
    legend: [
      { question: '<ruby>始皇帝<rt>しこうてい</rt></ruby>が<ruby>焚書<rt>ふんしょ</rt></ruby>で<ruby>実用書<rt>じつようしょ</rt></ruby>を<ruby>残<rt>のこ</rt></ruby>した<ruby>理由<rt>りゆう</rt></ruby>は？', choices: ['<ruby>合理的<rt>ごうりてき</rt></ruby>な<ruby>判断<rt>はんだん</rt></ruby>', '<ruby>忘<rt>わす</rt></ruby>れていた', '<ruby>部下<rt>ぶか</rt></ruby>が<ruby>隠<rt>かく</rt></ruby>した', '<ruby>法律<rt>ほうりつ</rt></ruby>で<ruby>決<rt>き</rt></ruby>まっていた'], correctIndex: 0 },
      { question: '<ruby>兵馬俑<rt>へいばよう</rt></ruby>が2,000<ruby>年<rt>ねん</rt></ruby><ruby>以上<rt>いじょう</rt></ruby><ruby>発見<rt>はっけん</rt></ruby>されなかった<ruby>理由<rt>りゆう</rt></ruby>は？', choices: ['<ruby>地下深<rt>ちかふか</rt></ruby>くに<ruby>埋<rt>う</rt></ruby>まっていた', '<ruby>海<rt>うみ</rt></ruby>の<ruby>底<rt>そこ</rt></ruby>にあった', '<ruby>外国<rt>がいこく</rt></ruby>にあった', '<ruby>小<rt>ちい</rt></ruby>さすぎた'], correctIndex: 0 },
      { question: '<ruby>紙<rt>かみ</rt></ruby>の<ruby>発明<rt>はつめい</rt></ruby>が<ruby>世界<rt>せかい</rt></ruby>を<ruby>変<rt>か</rt></ruby>えた<ruby>最大<rt>さいだい</rt></ruby>の<ruby>理由<rt>りゆう</rt></ruby>は？', choices: ['<ruby>知識<rt>ちしき</rt></ruby>を<ruby>広<rt>ひろ</rt></ruby>く<ruby>伝<rt>つた</rt></ruby>えられるようになった', '<ruby>軽<rt>かる</rt></ruby>くなった', '<ruby>安<rt>やす</rt></ruby>くなった', 'きれいになった'], correctIndex: 0 },
      { question: '<ruby>始皇帝<rt>しこうてい</rt></ruby>が「<ruby>最初<rt>さいしょ</rt></ruby>の<ruby>皇帝<rt>こうてい</rt></ruby>」と<ruby>自称<rt>じしょう</rt></ruby>した<ruby>意図<rt>いと</rt></ruby>は？', choices: ['<ruby>自分<rt>じぶん</rt></ruby>の<ruby>後<rt>あと</rt></ruby>にずっと<ruby>続<rt>つづ</rt></ruby>く<ruby>王朝<rt>おうちょう</rt></ruby>を<ruby>作<rt>つく</rt></ruby>りたかった', '<ruby>謙遜<rt>けんそん</rt></ruby>した', '<ruby>冗談<rt>じょうだん</rt></ruby>だった', '<ruby>他<rt>ほか</rt></ruby>の<ruby>人<rt>ひと</rt></ruby>に<ruby>命令<rt>めいれい</rt></ruby>された'], correctIndex: 0 },
      { question: '<ruby>万里<rt>ばんり</rt></ruby>の<ruby>長城<rt>ちょうじょう</rt></ruby>の<ruby>建設<rt>けんせつ</rt></ruby>で<ruby>起<rt>お</rt></ruby>きた<ruby>悲劇<rt>ひげき</rt></ruby>は？', choices: ['<ruby>多<rt>おお</rt></ruby>くの<ruby>人<rt>ひと</rt></ruby>が<ruby>命<rt>いのち</rt></ruby>を<ruby>落<rt>お</rt></ruby>とした', 'お<ruby>金<rt>かね</rt></ruby>がなくなった', '<ruby>戦争<rt>せんそう</rt></ruby>に<ruby>負<rt>ま</rt></ruby>けた', '<ruby>何<rt>なに</rt></ruby>も<ruby>起<rt>お</rt></ruby>きなかった'], correctIndex: 0 },
    ],
  },

  // ================================================================
  // 🔭 ガリレオ
  // ================================================================
  galileo: {
    beginner: [
      { question: 'ガリレオは<ruby>何<rt>なに</rt></ruby>を<ruby>使<rt>つか</rt></ruby>って<ruby>空<rt>そら</rt></ruby>を<ruby>観察<rt>かんさつ</rt></ruby>した？', choices: ['<ruby>望遠鏡<rt>ぼうえんきょう</rt></ruby>', '<ruby>顕微鏡<rt>けんびきょう</rt></ruby>', 'カメラ', '<ruby>目<rt>め</rt></ruby>だけ'], correctIndex: 0 },
      { question: 'ガリレオが<ruby>証明<rt>しょうめい</rt></ruby>したのは<ruby>何<rt>なに</rt></ruby>が<ruby>何<rt>なに</rt></ruby>の<ruby>周<rt>まわ</rt></ruby>りを<ruby>回<rt>まわ</rt></ruby>っている？', choices: ['<ruby>地球<rt>ちきゅう</rt></ruby>が<ruby>太陽<rt>たいよう</rt></ruby>の<ruby>周<rt>まわ</rt></ruby>り', '<ruby>太陽<rt>たいよう</rt></ruby>が<ruby>地球<rt>ちきゅう</rt></ruby>の<ruby>周<rt>まわ</rt></ruby>り', '<ruby>月<rt>つき</rt></ruby>が<ruby>太陽<rt>たいよう</rt></ruby>の<ruby>周<rt>まわ</rt></ruby>り', '<ruby>星<rt>ほし</rt></ruby>が<ruby>月<rt>つき</rt></ruby>の<ruby>周<rt>まわ</rt></ruby>り'], correctIndex: 0 },
      { question: 'ガリレオの<ruby>有名<rt>ゆうめい</rt></ruby>な<ruby>言葉<rt>ことば</rt></ruby>は？', choices: ['それでも<ruby>地球<rt>ちきゅう</rt></ruby>は<ruby>動<rt>うご</rt></ruby>いている', '<ruby>地球<rt>ちきゅう</rt></ruby>は<ruby>平<rt>たい</rt></ruby>らだ', '<ruby>太陽<rt>たいよう</rt></ruby>は<ruby>冷<rt>つめ</rt></ruby>たい', '<ruby>月<rt>つき</rt></ruby>は<ruby>近<rt>ちか</rt></ruby>い'], correctIndex: 0 },
      { question: 'ガリレオが<ruby>裁判<rt>さいばん</rt></ruby>にかけられた<ruby>理由<rt>りゆう</rt></ruby>は？', choices: ['<ruby>教会<rt>きょうかい</rt></ruby>に<ruby>逆<rt>さか</rt></ruby>らったから', '<ruby>人<rt>ひと</rt></ruby>を<ruby>傷<rt>きず</rt></ruby>つけたから', 'お<ruby>金<rt>かね</rt></ruby>を<ruby>盗<rt>ぬす</rt></ruby>んだから', '<ruby>嘘<rt>うそ</rt></ruby>をついたから'], correctIndex: 0 },
      { question: 'ガリレオが<ruby>最初<rt>さいしょ</rt></ruby>に<ruby>目指<rt>めざ</rt></ruby>していた<ruby>職業<rt>しょくぎょう</rt></ruby>は？', choices: ['<ruby>医者<rt>いしゃ</rt></ruby>', '<ruby>軍人<rt>ぐんじん</rt></ruby>', '<ruby>商人<rt>しょうにん</rt></ruby>', '<ruby>農家<rt>のうか</rt></ruby>'], correctIndex: 0 },
    ],
    challenger: [
      { question: 'ガリレオが<ruby>大学<rt>だいがく</rt></ruby>で<ruby>夢中<rt>むちゅう</rt></ruby>になったのは？', choices: ['<ruby>数学<rt>すうがく</rt></ruby>と<ruby>物理<rt>ぶつり</rt></ruby>', '<ruby>歴史<rt>れきし</rt></ruby>', '<ruby>文学<rt>ぶんがく</rt></ruby>', '<ruby>音楽<rt>おんがく</rt></ruby>'], correctIndex: 0 },
      { question: '「<ruby>地球<rt>ちきゅう</rt></ruby>が<ruby>宇宙<rt>うちゅう</rt></ruby>の<ruby>中心<rt>ちゅうしん</rt></ruby>」という<ruby>考<rt>かんが</rt></ruby>えを<ruby>何<rt>なに</rt></ruby>という？', choices: ['<ruby>天動説<rt>てんどうせつ</rt></ruby>', '<ruby>地動説<rt>ちどうせつ</rt></ruby>', '<ruby>万有引力<rt>ばんゆういんりょく</rt></ruby>', '<ruby>相対性理論<rt>そうたいせいりろん</rt></ruby>'], correctIndex: 0 },
      { question: 'ガリレオが<ruby>望遠鏡<rt>ぼうえんきょう</rt></ruby>で<ruby>発見<rt>はっけん</rt></ruby>した<ruby>木星<rt>もくせい</rt></ruby>の<ruby>衛星<rt>えいせい</rt></ruby>は<ruby>何個<rt>なんこ</rt></ruby>？', choices: ['4<ruby>個<rt>こ</rt></ruby>', '1<ruby>個<rt>こ</rt></ruby>', '10<ruby>個<rt>こ</rt></ruby>', '100<ruby>個<rt>こ</rt></ruby>'], correctIndex: 0 },
      { question: '<ruby>地動説<rt>ちどうせつ</rt></ruby>を<ruby>最初<rt>さいしょ</rt></ruby>に<ruby>唱<rt>とな</rt></ruby>えたのは？', choices: ['コペルニクス', 'ガリレオ', 'ニュートン', 'アインシュタイン'], correctIndex: 0 },
      { question: 'ガリレオが<ruby>望遠鏡<rt>ぼうえんきょう</rt></ruby>で<ruby>月<rt>つき</rt></ruby>に<ruby>見<rt>み</rt></ruby>つけたものは？', choices: ['クレーター', '<ruby>海<rt>うみ</rt></ruby>', '<ruby>生物<rt>せいぶつ</rt></ruby>', '<ruby>空気<rt>くうき</rt></ruby>'], correctIndex: 0 },
    ],
    master: [
      { question: 'ガリレオが<ruby>大学<rt>だいがく</rt></ruby>で<ruby>医学<rt>いがく</rt></ruby>ではなく<ruby>数学<rt>すうがく</rt></ruby>に<ruby>夢中<rt>むちゅう</rt></ruby>になったきっかけは？', choices: ['<ruby>授業中<rt>じゅぎょうちゅう</rt></ruby>に<ruby>数学<rt>すうがく</rt></ruby>の<ruby>本<rt>ほん</rt></ruby>ばかり<ruby>読<rt>よ</rt></ruby>んでいた', '<ruby>先生<rt>せんせい</rt></ruby>に<ruby>勧<rt>すす</rt></ruby>められた', '<ruby>試験<rt>しけん</rt></ruby>に<ruby>落<rt>お</rt></ruby>ちた', '<ruby>病気<rt>びょうき</rt></ruby>になった'], correctIndex: 0 },
      { question: '<ruby>木星<rt>もくせい</rt></ruby>の4つの<ruby>衛星<rt>えいせい</rt></ruby>は<ruby>今<rt>いま</rt></ruby><ruby>何<rt>なん</rt></ruby>と<ruby>呼<rt>よ</rt></ruby>ばれている？', choices: ['ガリレオ<ruby>衛星<rt>えいせい</rt></ruby>', '<ruby>木星衛星<rt>もくせいえいせい</rt></ruby>', '<ruby>太陽衛星<rt>たいようえいせい</rt></ruby>', 'コペルニクス<ruby>衛星<rt>えいせい</rt></ruby>'], correctIndex: 0 },
      { question: 'ガリレオの<ruby>名誉<rt>めいよ</rt></ruby>が<ruby>回復<rt>かいふく</rt></ruby>されたのは<ruby>何年後<rt>なんねんご</rt></ruby>？', choices: ['359<ruby>年後<rt>ねんご</rt></ruby>', '10<ruby>年後<rt>ねんご</rt></ruby>', '50<ruby>年後<rt>ねんご</rt></ruby>', '1,000<ruby>年後<rt>ねんご</rt></ruby>'], correctIndex: 0 },
      { question: 'ガリレオの<ruby>名誉<rt>めいよ</rt></ruby>を<ruby>回復<rt>かいふく</rt></ruby>したのは？', choices: ['ローマ<ruby>教皇<rt>きょうこう</rt></ruby>ヨハネ・パウロ2<ruby>世<rt>せい</rt></ruby>', 'イギリス<ruby>女王<rt>じょおう</rt></ruby>', 'アメリカ<ruby>大統領<rt>だいとうりょう</rt></ruby>', '<ruby>国連<rt>こくれん</rt></ruby>'], correctIndex: 0 },
      { question: '<ruby>月<rt>つき</rt></ruby>にクレーターがあることが<ruby>当時<rt>とうじ</rt></ruby><ruby>衝撃的<rt>しょうげきてき</rt></ruby>だった<ruby>理由<rt>りゆう</rt></ruby>は？', choices: ['<ruby>天体<rt>てんたい</rt></ruby>は<ruby>完璧<rt>かんぺき</rt></ruby>な<ruby>球体<rt>きゅうたい</rt></ruby>だと<ruby>信<rt>しん</rt></ruby>じられていたから', '<ruby>醜<rt>みにく</rt></ruby>いから', '<ruby>危険<rt>きけん</rt></ruby>だから', 'ありえないから'], correctIndex: 0 },
    ],
    legend: [
      { question: 'ガリレオが「<ruby>証拠<rt>しょうこ</rt></ruby>を<ruby>示<rt>しめ</rt></ruby>した」ことがコペルニクスとの<ruby>違<rt>ちが</rt></ruby>いである<ruby>理由<rt>りゆう</rt></ruby>は？', choices: ['<ruby>理論<rt>りろん</rt></ruby>だけでなく<ruby>観察<rt>かんさつ</rt></ruby>で<ruby>実証<rt>じっしょう</rt></ruby>したから', '<ruby>声<rt>こえ</rt></ruby>が<ruby>大<rt>おお</rt></ruby>きかったから', '<ruby>有名<rt>ゆうめい</rt></ruby>だったから', 'お<ruby>金<rt>かね</rt></ruby>があったから'], correctIndex: 0 },
      { question: '<ruby>教会<rt>きょうかい</rt></ruby>がガリレオを<ruby>裁判<rt>さいばん</rt></ruby>にかけた<ruby>根本的<rt>こんぽんてき</rt></ruby>な<ruby>理由<rt>りゆう</rt></ruby>は？', choices: ['<ruby>教会<rt>きょうかい</rt></ruby>の<ruby>教<rt>おし</rt></ruby>えと<ruby>科学<rt>かがく</rt></ruby>の<ruby>発見<rt>はっけん</rt></ruby>が<ruby>矛盾<rt>むじゅん</rt></ruby>したから', '<ruby>個人的<rt>こじんてき</rt></ruby>な<ruby>恨<rt>うら</rt></ruby>み', 'お<ruby>金<rt>かね</rt></ruby>の<ruby>問題<rt>もんだい</rt></ruby>', '<ruby>外国<rt>がいこく</rt></ruby>のスパイ'], correctIndex: 0 },
      { question: '<ruby>名誉回復<rt>めいよかいふく</rt></ruby>に359<ruby>年<rt>ねん</rt></ruby>かかったことが<ruby>示<rt>しめ</rt></ruby>すものは？', choices: ['<ruby>権力<rt>けんりょく</rt></ruby>と<ruby>真実<rt>しんじつ</rt></ruby>の<ruby>対立<rt>たいりつ</rt></ruby>の<ruby>根深<rt>ねぶか</rt></ruby>さ', '<ruby>特<rt>とく</rt></ruby>に<ruby>意味<rt>いみ</rt></ruby>はない', '<ruby>教会<rt>きょうかい</rt></ruby>が<ruby>忘<rt>わす</rt></ruby>れていた', '<ruby>手続<rt>てつづ</rt></ruby>きが<ruby>遅<rt>おそ</rt></ruby>いだけ'], correctIndex: 0 },
      { question: 'ガリレオの「それでも<ruby>地球<rt>ちきゅう</rt></ruby>は<ruby>動<rt>うご</rt></ruby>いている」が<ruby>象徴<rt>しょうちょう</rt></ruby>することは？', choices: ['<ruby>真実<rt>しんじつ</rt></ruby>は<ruby>権力<rt>けんりょく</rt></ruby>では<ruby>変<rt>か</rt></ruby>えられない', '<ruby>負<rt>ま</rt></ruby>け<ruby>惜<rt>お</rt></ruby>しみ', '<ruby>冗談<rt>じょうだん</rt></ruby>', '<ruby>教会<rt>きょうかい</rt></ruby>への<ruby>謝罪<rt>しゃざい</rt></ruby>'], correctIndex: 0 },
      { question: 'ガリレオの<ruby>物語<rt>ものがたり</rt></ruby>から<ruby>学<rt>まな</rt></ruby>べる<ruby>最<rt>もっと</rt></ruby>も<ruby>大切<rt>たいせつ</rt></ruby>なことは？', choices: ['<ruby>観察<rt>かんさつ</rt></ruby>と<ruby>証拠<rt>しょうこ</rt></ruby>に<ruby>基<rt>もと</rt></ruby>づいて<ruby>真実<rt>しんじつ</rt></ruby>を<ruby>追求<rt>ついきゅう</rt></ruby>する<ruby>姿勢<rt>しせい</rt></ruby>', '<ruby>権力<rt>けんりょく</rt></ruby>に<ruby>従<rt>したが</rt></ruby>うべき', '<ruby>科学<rt>かがく</rt></ruby>は<ruby>危険<rt>きけん</rt></ruby>', '<ruby>教会<rt>きょうかい</rt></ruby>が<ruby>正<rt>ただ</rt></ruby>しい'], correctIndex: 0 },
    ],
  },

  // ================================================================
  // 🗡️ ジャンヌ・ダルク
  // ================================================================
  jeanne: {
    beginner: [
      { question: 'ジャンヌダルクはどこの<ruby>国<rt>くに</rt></ruby>の<ruby>人<rt>ひと</rt></ruby>？', choices: ['フランス', 'イギリス', 'ドイツ', 'スペイン'], correctIndex: 0 },
      { question: 'ジャンヌが<ruby>神<rt>かみ</rt></ruby>の<ruby>声<rt>こえ</rt></ruby>を<ruby>聞<rt>き</rt></ruby>いたのは<ruby>何歳<rt>なんさい</rt></ruby>？', choices: ['13<ruby>歳<rt>さい</rt></ruby>', '5<ruby>歳<rt>さい</rt></ruby>', '25<ruby>歳<rt>さい</rt></ruby>', '30<ruby>歳<rt>さい</rt></ruby>'], correctIndex: 0 },
      { question: '<ruby>百年戦争<rt>ひゃくねんせんそう</rt></ruby>の<ruby>相手<rt>あいて</rt></ruby>はどこの<ruby>国<rt>くに</rt></ruby>？', choices: ['イギリス', 'ドイツ', 'スペイン', 'ロシア'], correctIndex: 0 },
      { question: 'ジャンヌが<ruby>解放<rt>かいほう</rt></ruby>した<ruby>都市<rt>とし</rt></ruby>は？', choices: ['オルレアン', 'パリ', 'ロンドン', 'ローマ'], correctIndex: 0 },
      { question: 'ジャンヌはどのように<ruby>亡<rt>な</rt></ruby>くなった？', choices: ['<ruby>火刑<rt>かけい</rt></ruby>', '<ruby>戦死<rt>せんし</rt></ruby>', '<ruby>老衰<rt>ろうすい</rt></ruby>', '<ruby>病死<rt>びょうし</rt></ruby>'], correctIndex: 0 },
    ],
    challenger: [
      { question: 'ジャンヌが<ruby>軍<rt>ぐん</rt></ruby>を<ruby>率<rt>ひき</rt></ruby>いた<ruby>時<rt>とき</rt></ruby>の<ruby>年齢<rt>ねんれい</rt></ruby>は？', choices: ['17<ruby>歳<rt>さい</rt></ruby>', '25<ruby>歳<rt>さい</rt></ruby>', '30<ruby>歳<rt>さい</rt></ruby>', '13<ruby>歳<rt>さい</rt></ruby>'], correctIndex: 0 },
      { question: '<ruby>百年戦争<rt>ひゃくねんせんそう</rt></ruby>は<ruby>実際<rt>じっさい</rt></ruby>には<ruby>何年<rt>なんねん</rt></ruby><ruby>続<rt>つづ</rt></ruby>いた？', choices: ['116<ruby>年<rt>ねん</rt></ruby>', '100<ruby>年<rt>ねん</rt></ruby>', '50<ruby>年<rt>ねん</rt></ruby>', '200<ruby>年<rt>ねん</rt></ruby>'], correctIndex: 0 },
      { question: 'オルレアンの<ruby>包囲<rt>ほうい</rt></ruby>を<ruby>何日<rt>なんにち</rt></ruby>で<ruby>突破<rt>とっぱ</rt></ruby>した？', choices: ['9<ruby>日<rt>にち</rt></ruby>', '30<ruby>日<rt>にち</rt></ruby>', '1<ruby>日<rt>にち</rt></ruby>', '100<ruby>日<rt>にち</rt></ruby>'], correctIndex: 0 },
      { question: 'ジャンヌが<ruby>火刑<rt>かけい</rt></ruby>にされた<ruby>理由<rt>りゆう</rt></ruby>は？', choices: ['<ruby>魔女<rt>まじょ</rt></ruby>として<ruby>裁<rt>さば</rt></ruby>かれた', '<ruby>戦争<rt>せんそう</rt></ruby>に<ruby>負<rt>ま</rt></ruby>けた', '<ruby>王<rt>おう</rt></ruby>に<ruby>逆<rt>さか</rt></ruby>らった', '<ruby>逃<rt>に</rt></ruby>げようとした'], correctIndex: 0 },
      { question: 'ジャンヌが「<ruby>聖女<rt>せいじょ</rt></ruby>」と<ruby>認<rt>みと</rt></ruby>められたのはいつ？', choices: ['500<ruby>年後<rt>ねんご</rt></ruby>', 'すぐに', '10<ruby>年後<rt>ねんご</rt></ruby>', '<ruby>認<rt>みと</rt></ruby>められていない'], correctIndex: 0 },
    ],
    master: [
      { question: 'ジャンヌは<ruby>読<rt>よ</rt></ruby>み<ruby>書<rt>か</rt></ruby>きができた？', choices: ['できなかった', 'できた', '<ruby>少<rt>すこ</rt></ruby>しだけ', 'ラテン<ruby>語<rt>ご</rt></ruby>だけ'], correctIndex: 0 },
      { question: 'ジャンヌが<ruby>戦場<rt>せんじょう</rt></ruby>で<ruby>矢<rt>や</rt></ruby>を<ruby>受<rt>う</rt></ruby>けた<ruby>場所<rt>ばしょ</rt></ruby>は？', choices: ['<ruby>肩<rt>かた</rt></ruby>', '<ruby>足<rt>あし</rt></ruby>', '<ruby>頭<rt>あたま</rt></ruby>', '<ruby>腕<rt>うで</rt></ruby>'], correctIndex: 0 },
      { question: 'ジャンヌの<ruby>裁判記録<rt>さいばんきろく</rt></ruby>は<ruby>今<rt>いま</rt></ruby>どうなっている？', choices: ['<ruby>今<rt>いま</rt></ruby>も<ruby>残<rt>のこ</rt></ruby>っていて<ruby>読<rt>よ</rt></ruby>める', '<ruby>失<rt>うしな</rt></ruby>われた', '<ruby>偽物<rt>にせもの</rt></ruby>しかない', '<ruby>秘密<rt>ひみつ</rt></ruby>にされている'], correctIndex: 0 },
      { question: 'ジャンヌを「<ruby>聖女<rt>せいじょ</rt></ruby>」と<ruby>認<rt>みと</rt></ruby>めたのは？', choices: ['カトリック<ruby>教会<rt>きょうかい</rt></ruby>', 'フランス<ruby>政府<rt>せいふ</rt></ruby>', 'イギリス<ruby>王<rt>おう</rt></ruby>', '<ruby>国連<rt>こくれん</rt></ruby>'], correctIndex: 0 },
      { question: '<ruby>百年戦争<rt>ひゃくねんせんそう</rt></ruby>の<ruby>途中<rt>とちゅう</rt></ruby>にあったことは？', choices: ['<ruby>何度<rt>なんど</rt></ruby>か<ruby>休戦<rt>きゅうせん</rt></ruby>した', 'ずっと<ruby>戦<rt>たたか</rt></ruby>い<ruby>続<rt>つづ</rt></ruby>けた', '3<ruby>回<rt>かい</rt></ruby>だけ<ruby>戦<rt>たたか</rt></ruby>った', '1<ruby>年<rt>ねん</rt></ruby>で<ruby>終<rt>お</rt></ruby>わった'], correctIndex: 0 },
    ],
    legend: [
      { question: '<ruby>読<rt>よ</rt></ruby>み<ruby>書<rt>か</rt></ruby>きできないジャンヌが<ruby>軍<rt>ぐん</rt></ruby>を<ruby>指揮<rt>しき</rt></ruby>できた<ruby>理由<rt>りゆう</rt></ruby>は？', choices: ['<ruby>神<rt>かみ</rt></ruby>の<ruby>声<rt>こえ</rt></ruby>への<ruby>確信<rt>かくしん</rt></ruby>と<ruby>勇気<rt>ゆうき</rt></ruby>が<ruby>兵士<rt>へいし</rt></ruby>を<ruby>動<rt>うご</rt></ruby>かした', '<ruby>魔法<rt>まほう</rt></ruby>を<ruby>使<rt>つか</rt></ruby>った', 'お<ruby>金<rt>かね</rt></ruby>で<ruby>雇<rt>やと</rt></ruby>った', '<ruby>嘘<rt>うそ</rt></ruby>をついた'], correctIndex: 0 },
      { question: 'ジャンヌの<ruby>火刑<rt>かけい</rt></ruby>が<ruby>歴史的<rt>れきしてき</rt></ruby>に<ruby>重要<rt>じゅうよう</rt></ruby>な<ruby>理由<rt>りゆう</rt></ruby>は？', choices: ['500<ruby>年後<rt>ねんご</rt></ruby>に<ruby>名誉<rt>めいよ</rt></ruby><ruby>回復<rt>かいふく</rt></ruby>され<ruby>正義<rt>せいぎ</rt></ruby>が<ruby>問<rt>と</rt></ruby>い<ruby>直<rt>なお</rt></ruby>された', '<ruby>特<rt>とく</rt></ruby>に<ruby>重要<rt>じゅうよう</rt></ruby>でない', '<ruby>戦争<rt>せんそう</rt></ruby>が<ruby>終<rt>お</rt></ruby>わった', 'フランスが<ruby>負<rt>ま</rt></ruby>けた'], correctIndex: 0 },
      { question: 'ジャンヌの<ruby>裁判記録<rt>さいばんきろく</rt></ruby>が<ruby>残<rt>のこ</rt></ruby>っていることの<ruby>価値<rt>かち</rt></ruby>は？', choices: ['<ruby>本人<rt>ほんにん</rt></ruby>の<ruby>言葉<rt>ことば</rt></ruby>を<ruby>今<rt>いま</rt></ruby>も<ruby>読<rt>よ</rt></ruby>める<ruby>歴史的<rt>れきしてき</rt></ruby><ruby>証拠<rt>しょうこ</rt></ruby>', '<ruby>特<rt>とく</rt></ruby>に<ruby>価値<rt>かち</rt></ruby>はない', '<ruby>偽造<rt>ぎぞう</rt></ruby>の<ruby>証拠<rt>しょうこ</rt></ruby>', 'イギリスの<ruby>宣伝<rt>せんでん</rt></ruby>'], correctIndex: 0 },
      { question: '<ruby>百年戦争<rt>ひゃくねんせんそう</rt></ruby>でジャンヌが「<ruby>流<rt>なが</rt></ruby>れを<ruby>変<rt>か</rt></ruby>えた」とはどういう<ruby>意味<rt>いみ</rt></ruby>？', choices: ['<ruby>負<rt>ま</rt></ruby>けそうだったフランスを<ruby>勝利<rt>しょうり</rt></ruby>に<ruby>導<rt>みちび</rt></ruby>いた', '<ruby>戦争<rt>せんそう</rt></ruby>を<ruby>長引<rt>ながび</rt></ruby>かせた', '<ruby>和平<rt>わへい</rt></ruby>を<ruby>結<rt>むす</rt></ruby>んだ', '<ruby>逃<rt>に</rt></ruby>げた'], correctIndex: 0 },
      { question: 'ジャンヌが<ruby>農村<rt>のうそん</rt></ruby>の<ruby>少女<rt>しょうじょ</rt></ruby>から<ruby>英雄<rt>えいゆう</rt></ruby>になれた<ruby>最大<rt>さいだい</rt></ruby>の<ruby>理由<rt>りゆう</rt></ruby>は？', choices: ['<ruby>自分<rt>じぶん</rt></ruby>の<ruby>信念<rt>しんねん</rt></ruby>を<ruby>貫<rt>つらぬ</rt></ruby>き<ruby>周<rt>まわ</rt></ruby>りを<ruby>動<rt>うご</rt></ruby>かしたから', '<ruby>身分<rt>みぶん</rt></ruby>が<ruby>高<rt>たか</rt></ruby>かったから', '<ruby>武術<rt>ぶじゅつ</rt></ruby>が<ruby>得意<rt>とくい</rt></ruby>だったから', 'お<ruby>金<rt>かね</rt></ruby>があったから'], correctIndex: 0 },
    ],
  },

  // ================================================================
  // 📖 紫式部
  // ================================================================
  murasaki: {
    beginner: [
      { question: '<ruby>紫式部<rt>むらさきしきぶ</rt></ruby>が<ruby>書<rt>か</rt></ruby>いた<ruby>有名<rt>ゆうめい</rt></ruby>な<ruby>小説<rt>しょうせつ</rt></ruby>は？', choices: ['<ruby>源氏物語<rt>げんじものがたり</rt></ruby>', '<ruby>枕草子<rt>まくらのそうし</rt></ruby>', '<ruby>竹取物語<rt>たけとりものがたり</rt></ruby>', '<ruby>万葉集<rt>まんようしゅう</rt></ruby>'], correctIndex: 0 },
      { question: '<ruby>紫式部<rt>むらさきしきぶ</rt></ruby>はいつの<ruby>時代<rt>じだい</rt></ruby>の<ruby>人<rt>ひと</rt></ruby>？', choices: ['<ruby>平安時代<rt>へいあんじだい</rt></ruby>', '<ruby>江戸時代<rt>えどじだい</rt></ruby>', '<ruby>鎌倉時代<rt>かまくらじだい</rt></ruby>', '<ruby>奈良時代<rt>ならじだい</rt></ruby>'], correctIndex: 0 },
      { question: '<ruby>源氏物語<rt>げんじものがたり</rt></ruby>の<ruby>主人公<rt>しゅじんこう</rt></ruby>の<ruby>名前<rt>なまえ</rt></ruby>は？', choices: ['<ruby>光源氏<rt>ひかるげんじ</rt></ruby>', '<ruby>紫式部<rt>むらさきしきぶ</rt></ruby>', '<ruby>清少納言<rt>せいしょうなごん</rt></ruby>', '<ruby>藤原道長<rt>ふじわらのみちなが</rt></ruby>'], correctIndex: 0 },
      { question: '<ruby>平安時代<rt>へいあんじだい</rt></ruby>の<ruby>貴族<rt>きぞく</rt></ruby>が<ruby>気持<rt>きも</rt></ruby>ちを<ruby>伝<rt>つた</rt></ruby>えるのに<ruby>使<rt>つか</rt></ruby>ったものは？', choices: ['<ruby>和歌<rt>わか</rt></ruby>', '<ruby>手紙<rt>てがみ</rt></ruby>', '<ruby>電話<rt>でんわ</rt></ruby>', '<ruby>絵<rt>え</rt></ruby>'], correctIndex: 0 },
      { question: '<ruby>漢字<rt>かんじ</rt></ruby>をくずして<ruby>生<rt>う</rt></ruby>まれた<ruby>文字<rt>もじ</rt></ruby>は？', choices: ['ひらがな', 'カタカナ', 'アルファベット', '<ruby>数字<rt>すうじ</rt></ruby>'], correctIndex: 0 },
    ],
    challenger: [
      { question: '<ruby>源氏物語<rt>げんじものがたり</rt></ruby>は<ruby>全部<rt>ぜんぶ</rt></ruby>で<ruby>何巻<rt>なんかん</rt></ruby>？', choices: ['54<ruby>巻<rt>かん</rt></ruby>', '10<ruby>巻<rt>かん</rt></ruby>', '100<ruby>巻<rt>かん</rt></ruby>', '20<ruby>巻<rt>かん</rt></ruby>'], correctIndex: 0 },
      { question: '「<ruby>紫式部<rt>むらさきしきぶ</rt></ruby>」は<ruby>本名<rt>ほんみょう</rt></ruby>？', choices: ['ペンネーム', '<ruby>本名<rt>ほんみょう</rt></ruby>', 'あだ<ruby>名<rt>な</rt></ruby>', '<ruby>官職名<rt>かんしょくめい</rt></ruby>'], correctIndex: 0 },
      { question: '<ruby>平安時代<rt>へいあんじだい</rt></ruby>の<ruby>貴族<rt>きぞく</rt></ruby>の<ruby>女性<rt>じょせい</rt></ruby>がしていたマナーは？', choices: ['<ruby>顔<rt>かお</rt></ruby>を<ruby>見<rt>み</rt></ruby>せない', '<ruby>大声<rt>おおごえ</rt></ruby>で<ruby>話<rt>はな</rt></ruby>す', '<ruby>走<rt>はし</rt></ruby>り<ruby>回<rt>まわ</rt></ruby>る', '<ruby>髪<rt>かみ</rt></ruby>を<ruby>短<rt>みじか</rt></ruby>くする'], correctIndex: 0 },
      { question: 'ひらがなは<ruby>最初<rt>さいしょ</rt></ruby><ruby>何<rt>なん</rt></ruby>と<ruby>呼<rt>よ</rt></ruby>ばれた？', choices: ['<ruby>女手<rt>おんなで</rt></ruby>', '<ruby>男手<rt>おとこで</rt></ruby>', '<ruby>子供手<rt>こどもで</rt></ruby>', '<ruby>天手<rt>てんで</rt></ruby>'], correctIndex: 0 },
      { question: '<ruby>源氏物語<rt>げんじものがたり</rt></ruby>は<ruby>世界的<rt>せかいてき</rt></ruby>にどう<ruby>評価<rt>ひょうか</rt></ruby>されている？', choices: ['<ruby>世界最古<rt>せかいさいこ</rt></ruby>の<ruby>長編小説<rt>ちょうへんしょうせつ</rt></ruby>', '<ruby>普通<rt>ふつう</rt></ruby>の<ruby>小説<rt>しょうせつ</rt></ruby>', '<ruby>短<rt>みじか</rt></ruby>い<ruby>物語<rt>ものがたり</rt></ruby>', '<ruby>詩集<rt>ししゅう</rt></ruby>'], correctIndex: 0 },
    ],
    master: [
      { question: '<ruby>紫式部<rt>むらさきしきぶ</rt></ruby>の<ruby>本名<rt>ほんみょう</rt></ruby>は？', choices: ['<ruby>今<rt>いま</rt></ruby>もわかっていない', '<ruby>紫<rt>むらさき</rt></ruby>', '<ruby>式部<rt>しきぶ</rt></ruby>', '<ruby>花子<rt>はなこ</rt></ruby>'], correctIndex: 0 },
      { question: '<ruby>源氏物語<rt>げんじものがたり</rt></ruby>を<ruby>現代<rt>げんだい</rt></ruby>の<ruby>文庫本<rt>ぶんこぼん</rt></ruby>にすると<ruby>何冊<rt>なんさつ</rt></ruby><ruby>以上<rt>いじょう</rt></ruby>？', choices: ['10<ruby>冊以上<rt>さついじょう</rt></ruby>', '2<ruby>冊<rt>さつ</rt></ruby>', '100<ruby>冊<rt>さつ</rt></ruby>', '1<ruby>冊<rt>さつ</rt></ruby>'], correctIndex: 0 },
      { question: '<ruby>貴族<rt>きぞく</rt></ruby>の<ruby>女性<rt>じょせい</rt></ruby>が<ruby>顔<rt>かお</rt></ruby>を<ruby>隠<rt>かく</rt></ruby>すのに<ruby>使<rt>つか</rt></ruby>ったものは？', choices: ['<ruby>扇<rt>おうぎ</rt></ruby>や<ruby>御簾<rt>みす</rt></ruby>', 'マスク', '<ruby>帽子<rt>ぼうし</rt></ruby>', '<ruby>手<rt>て</rt></ruby>'], correctIndex: 0 },
      { question: 'ひらがなを<ruby>中心<rt>ちゅうしん</rt></ruby>に<ruby>使<rt>つか</rt></ruby>い<ruby>広<rt>ひろ</rt></ruby>めたのは？', choices: ['<ruby>女性<rt>じょせい</rt></ruby>たち', '<ruby>武士<rt>ぶし</rt></ruby>', '<ruby>僧侶<rt>そうりょ</rt></ruby>', '<ruby>農民<rt>のうみん</rt></ruby>'], correctIndex: 0 },
      { question: '<ruby>紫式部<rt>むらさきしきぶ</rt></ruby>の<ruby>本名<rt>ほんみょう</rt></ruby>がわからないのはなぜ<ruby>特別<rt>とくべつ</rt></ruby>？', choices: ['1,000<ruby>年最大<rt>ねんさいだい</rt></ruby>のミステリー', '<ruby>特<rt>とく</rt></ruby>に<ruby>珍<rt>めずら</rt></ruby>しくない', '<ruby>記録<rt>きろく</rt></ruby>が<ruby>焼<rt>や</rt></ruby>けた', '<ruby>本人<rt>ほんにん</rt></ruby>が<ruby>隠<rt>かく</rt></ruby>した'], correctIndex: 0 },
    ],
    legend: [
      { question: 'ひらがなの<ruby>誕生<rt>たんじょう</rt></ruby>がなければ<ruby>源氏物語<rt>げんじものがたり</rt></ruby>はどうなっていた？', choices: ['<ruby>書<rt>か</rt></ruby>けなかった<ruby>可能性<rt>かのうせい</rt></ruby>が<ruby>高<rt>たか</rt></ruby>い', '<ruby>何<rt>なに</rt></ruby>も<ruby>変<rt>か</rt></ruby>わらない', '<ruby>漢字<rt>かんじ</rt></ruby>で<ruby>書<rt>か</rt></ruby>いた', '<ruby>口伝<rt>くちづた</rt></ruby>えになった'], correctIndex: 0 },
      { question: '<ruby>源氏物語<rt>げんじものがたり</rt></ruby>が1,000<ruby>年<rt>ねん</rt></ruby><ruby>読<rt>よ</rt></ruby>み<ruby>続<rt>つづ</rt></ruby>けられている<ruby>理由<rt>りゆう</rt></ruby>は？', choices: ['<ruby>人間<rt>にんげん</rt></ruby>の<ruby>感情<rt>かんじょう</rt></ruby>を<ruby>深<rt>ふか</rt></ruby>く<ruby>描<rt>えが</rt></ruby>いているから', '<ruby>短<rt>みじか</rt></ruby>いから', '<ruby>簡単<rt>かんたん</rt></ruby>だから', '<ruby>命令<rt>めいれい</rt></ruby>されているから'], correctIndex: 0 },
      { question: '<ruby>平安時代<rt>へいあんじだい</rt></ruby>に「<ruby>美<rt>び</rt></ruby>」が<ruby>大切<rt>たいせつ</rt></ruby>にされたことの<ruby>意味<rt>いみ</rt></ruby>は？', choices: ['<ruby>文化<rt>ぶんか</rt></ruby>や<ruby>芸術<rt>げいじゅつ</rt></ruby>が<ruby>高度<rt>こうど</rt></ruby>に<ruby>発展<rt>はってん</rt></ruby>した<ruby>証拠<rt>しょうこ</rt></ruby>', '<ruby>無駄<rt>むだ</rt></ruby>だった', '<ruby>戦<rt>たたか</rt></ruby>いを<ruby>避<rt>さ</rt></ruby>けただけ', '<ruby>特<rt>とく</rt></ruby>に<ruby>意味<rt>いみ</rt></ruby>はない'], correctIndex: 0 },
      { question: 'ひらがなが「<ruby>女手<rt>おんなで</rt></ruby>」と<ruby>呼<rt>よ</rt></ruby>ばれた<ruby>背景<rt>はいけい</rt></ruby>は？', choices: ['<ruby>正式<rt>せいしき</rt></ruby>な<ruby>文書<rt>ぶんしょ</rt></ruby>は<ruby>漢字<rt>かんじ</rt></ruby>で<ruby>書<rt>か</rt></ruby>くものとされ<ruby>女性<rt>じょせい</rt></ruby>がひらがなを<ruby>使<rt>つか</rt></ruby>ったから', '<ruby>女性<rt>じょせい</rt></ruby>が<ruby>発明<rt>はつめい</rt></ruby>したから', '<ruby>男性<rt>だんせい</rt></ruby>は<ruby>文字<rt>もじ</rt></ruby>を<ruby>使<rt>つか</rt></ruby>わなかったから', '<ruby>法律<rt>ほうりつ</rt></ruby>で<ruby>決<rt>き</rt></ruby>まっていたから'], correctIndex: 0 },
      { question: '<ruby>紫式部<rt>むらさきしきぶ</rt></ruby>が<ruby>源氏物語<rt>げんじものがたり</rt></ruby>を<ruby>書<rt>か</rt></ruby>けた<ruby>社会的<rt>しゃかいてき</rt></ruby>な<ruby>条件<rt>じょうけん</rt></ruby>は？', choices: ['<ruby>宮廷<rt>きゅうてい</rt></ruby>に<ruby>仕<rt>つか</rt></ruby>えて<ruby>貴族文化<rt>きぞくぶんか</rt></ruby>を<ruby>直接<rt>ちょくせつ</rt></ruby><ruby>知<rt>し</rt></ruby>れたから', 'お<ruby>金持<rt>かねも</rt></ruby>ちだったから', '<ruby>命令<rt>めいれい</rt></ruby>されたから', '<ruby>暇<rt>ひま</rt></ruby>だったから'], correctIndex: 0 },
    ],
  },

  // ================================================================
  // 🌍 マンデラ
  // ================================================================
  mandela: {
    beginner: [
      { question: 'マンデラはどこの<ruby>国<rt>くに</rt></ruby>の<ruby>人<rt>ひと</rt></ruby>？', choices: ['<ruby>南<rt>みなみ</rt></ruby>アフリカ', 'アメリカ', 'イギリス', 'エジプト'], correctIndex: 0 },
      { question: 'アパルトヘイトとは<ruby>何<rt>なに</rt></ruby>？', choices: ['<ruby>肌<rt>はだ</rt></ruby>の<ruby>色<rt>いろ</rt></ruby>で<ruby>人<rt>ひと</rt></ruby>を<ruby>差別<rt>さべつ</rt></ruby>する<ruby>制度<rt>せいど</rt></ruby>', '<ruby>貿易<rt>ぼうえき</rt></ruby>の<ruby>仕組<rt>しく</rt></ruby>み', '<ruby>教育<rt>きょういく</rt></ruby>の<ruby>方法<rt>ほうほう</rt></ruby>', '<ruby>戦争<rt>せんそう</rt></ruby>の<ruby>名前<rt>なまえ</rt></ruby>'], correctIndex: 0 },
      { question: 'マンデラが<ruby>投獄<rt>とうごく</rt></ruby>されていた<ruby>期間<rt>きかん</rt></ruby>は？', choices: ['27<ruby>年<rt>ねん</rt></ruby>', '5<ruby>年<rt>ねん</rt></ruby>', '1<ruby>年<rt>ねん</rt></ruby>', '50<ruby>年<rt>ねん</rt></ruby>'], correctIndex: 0 },
      { question: 'マンデラは<ruby>何<rt>なに</rt></ruby>になった？', choices: ['<ruby>大統領<rt>だいとうりょう</rt></ruby>', '<ruby>王<rt>おう</rt></ruby>', '<ruby>将軍<rt>しょうぐん</rt></ruby>', '<ruby>医者<rt>いしゃ</rt></ruby>'], correctIndex: 0 },
      { question: 'マンデラが<ruby>大切<rt>たいせつ</rt></ruby>にしたことは？', choices: ['<ruby>赦<rt>ゆる</rt></ruby>し', '<ruby>復讐<rt>ふくしゅう</rt></ruby>', '<ruby>戦争<rt>せんそう</rt></ruby>', 'お<ruby>金<rt>かね</rt></ruby>'], correctIndex: 0 },
    ],
    challenger: [
      { question: 'マンデラが<ruby>投獄<rt>とうごく</rt></ruby>されていた<ruby>島<rt>しま</rt></ruby>の<ruby>名前<rt>なまえ</rt></ruby>は？', choices: ['ロベン<ruby>島<rt>とう</rt></ruby>', 'マダガスカル', 'ハワイ', 'セントヘレナ'], correctIndex: 0 },
      { question: 'アパルトヘイトでは<ruby>何<rt>なに</rt></ruby>が<ruby>分<rt>わ</rt></ruby>けられていた？', choices: ['バスも<ruby>学校<rt>がっこう</rt></ruby>もトイレも<ruby>全<rt>すべ</rt></ruby>て', '<ruby>食<rt>た</rt></ruby>べ<ruby>物<rt>もの</rt></ruby>だけ', '<ruby>家<rt>いえ</rt></ruby>だけ', '<ruby>仕事<rt>しごと</rt></ruby>だけ'], correctIndex: 0 },
      { question: 'マンデラが<ruby>大統領<rt>だいとうりょう</rt></ruby>になった<ruby>時<rt>とき</rt></ruby>の<ruby>年齢<rt>ねんれい</rt></ruby>は？', choices: ['76<ruby>歳<rt>さい</rt></ruby>', '50<ruby>歳<rt>さい</rt></ruby>', '30<ruby>歳<rt>さい</rt></ruby>', '90<ruby>歳<rt>さい</rt></ruby>'], correctIndex: 0 },
      { question: 'マンデラが<ruby>獄中<rt>ごくちゅう</rt></ruby>でも<ruby>続<rt>つづ</rt></ruby>けていたことは？', choices: ['<ruby>法律<rt>ほうりつ</rt></ruby>の<ruby>勉強<rt>べんきょう</rt></ruby>', '<ruby>運動<rt>うんどう</rt></ruby>', '<ruby>絵<rt>え</rt></ruby>を<ruby>描<rt>か</rt></ruby>く', '<ruby>音楽<rt>おんがく</rt></ruby>'], correctIndex: 0 },
      { question: '<ruby>南<rt>みなみ</rt></ruby>アフリカが「<ruby>虹<rt>にじ</rt></ruby>の<ruby>国<rt>くに</rt></ruby>」と<ruby>呼<rt>よ</rt></ruby>ばれる<ruby>理由<rt>りゆう</rt></ruby>は？', choices: ['<ruby>多民族<rt>たみんぞく</rt></ruby>が<ruby>共存<rt>きょうぞん</rt></ruby>しているから', '<ruby>虹<rt>にじ</rt></ruby>がよく<ruby>出<rt>で</rt></ruby>るから', '<ruby>国旗<rt>こっき</rt></ruby>が<ruby>虹色<rt>にじいろ</rt></ruby>だから', '<ruby>気候<rt>きこう</rt></ruby>がいいから'], correctIndex: 0 },
    ],
    master: [
      { question: 'アパルトヘイトが<ruby>続<rt>つづ</rt></ruby>いた<ruby>期間<rt>きかん</rt></ruby>は？', choices: ['43<ruby>年間<rt>ねんかん</rt></ruby>', '10<ruby>年間<rt>ねんかん</rt></ruby>', '100<ruby>年間<rt>ねんかん</rt></ruby>', '5<ruby>年間<rt>ねんかん</rt></ruby>'], correctIndex: 0 },
      { question: 'マンデラの<ruby>人生<rt>じんせい</rt></ruby>の3<ruby>分<rt>ぶん</rt></ruby>の1は<ruby>何<rt>なに</rt></ruby>に<ruby>費<rt>つい</rt></ruby>やされた？', choices: ['<ruby>刑務所<rt>けいむしょ</rt></ruby>', '<ruby>大学<rt>だいがく</rt></ruby>', '<ruby>旅行<rt>りょこう</rt></ruby>', '<ruby>政治<rt>せいじ</rt></ruby>'], correctIndex: 0 },
      { question: 'マンデラの<ruby>有名<rt>ゆうめい</rt></ruby>な<ruby>言葉<rt>ことば</rt></ruby>「<ruby>恨<rt>うら</rt></ruby>みを<ruby>持<rt>も</rt></ruby>ち<ruby>続<rt>つづ</rt></ruby>けることは…」の<ruby>続<rt>つづ</rt></ruby>きは？', choices: ['<ruby>自分<rt>じぶん</rt></ruby>を<ruby>牢獄<rt>ろうごく</rt></ruby>に<ruby>閉<rt>と</rt></ruby>じ<ruby>込<rt>こ</rt></ruby>め<ruby>続<rt>つづ</rt></ruby>けるのと<ruby>同<rt>おな</rt></ruby>じ', '<ruby>正<rt>ただ</rt></ruby>しいこと', '<ruby>強<rt>つよ</rt></ruby>さの<ruby>証<rt>あかし</rt></ruby>', '<ruby>必要<rt>ひつよう</rt></ruby>なこと'], correctIndex: 0 },
      { question: 'マンデラが<ruby>大統領<rt>だいとうりょう</rt></ruby>になった<ruby>後<rt>あと</rt></ruby>、<ruby>元看守<rt>もとかんしゅ</rt></ruby>にしたことは？', choices: ['<ruby>昼食<rt>ちゅうしょく</rt></ruby>に<ruby>招待<rt>しょうたい</rt></ruby>した', '<ruby>逮捕<rt>たいほ</rt></ruby>した', '<ruby>無視<rt>むし</rt></ruby>した', '<ruby>追<rt>お</rt></ruby>い<ruby>出<rt>だ</rt></ruby>した'], correctIndex: 0 },
      { question: '<ruby>刑務所<rt>けいむしょ</rt></ruby>の<ruby>看守<rt>かんしゅ</rt></ruby>たちがマンデラに<ruby>対<rt>たい</rt></ruby>してどう<ruby>変<rt>か</rt></ruby>わった？', choices: ['<ruby>尊敬<rt>そんけい</rt></ruby>するようになった', 'もっと<ruby>厳<rt>きび</rt></ruby>しくなった', '<ruby>何<rt>なに</rt></ruby>も<ruby>変<rt>か</rt></ruby>わらなかった', '<ruby>逃<rt>に</rt></ruby>がそうとした'], correctIndex: 0 },
    ],
    legend: [
      { question: 'マンデラの「<ruby>赦<rt>ゆる</rt></ruby>し」が<ruby>南<rt>みなみ</rt></ruby>アフリカを<ruby>変<rt>か</rt></ruby>えた<ruby>理由<rt>りゆう</rt></ruby>は？', choices: ['<ruby>報復<rt>ほうふく</rt></ruby>の<ruby>連鎖<rt>れんさ</rt></ruby>を<ruby>断<rt>た</rt></ruby>ち<ruby>切<rt>き</rt></ruby>り<ruby>共存<rt>きょうぞん</rt></ruby>の<ruby>道<rt>みち</rt></ruby>を<ruby>開<rt>ひら</rt></ruby>いたから', '<ruby>弱<rt>よわ</rt></ruby>さだった', '<ruby>意味<rt>いみ</rt></ruby>がなかった', '<ruby>外国<rt>がいこく</rt></ruby>の<ruby>命令<rt>めいれい</rt></ruby>'], correctIndex: 0 },
      { question: '27<ruby>年間<rt>ねんかん</rt></ruby><ruby>投獄<rt>とうごく</rt></ruby>されても<ruby>折<rt>お</rt></ruby>れなかったマンデラの<ruby>強<rt>つよ</rt></ruby>さの<ruby>源<rt>みなもと</rt></ruby>は？', choices: ['<ruby>正義<rt>せいぎ</rt></ruby>への<ruby>信念<rt>しんねん</rt></ruby>と<ruby>学<rt>まな</rt></ruby>び<ruby>続<rt>つづ</rt></ruby>ける<ruby>姿勢<rt>しせい</rt></ruby>', '<ruby>体力<rt>たいりょく</rt></ruby>', 'お<ruby>金<rt>かね</rt></ruby>', '<ruby>仲間<rt>なかま</rt></ruby>の<ruby>裏切<rt>うらぎ</rt></ruby>り'], correctIndex: 0 },
      { question: 'アパルトヘイトが「<ruby>生<rt>う</rt></ruby>まれた<ruby>時<rt>とき</rt></ruby>から<ruby>差別<rt>さべつ</rt></ruby>が<ruby>当<rt>あ</rt></ruby>たり<ruby>前<rt>まえ</rt></ruby>の<ruby>社会<rt>しゃかい</rt></ruby>」だった<ruby>意味<rt>いみ</rt></ruby>は？', choices: ['43<ruby>年<rt>ねん</rt></ruby><ruby>続<rt>つづ</rt></ruby>いたので<ruby>差別<rt>さべつ</rt></ruby>を<ruby>知<rt>し</rt></ruby>らない<ruby>世代<rt>せだい</rt></ruby>が<ruby>育<rt>そだ</rt></ruby>った', '<ruby>特<rt>とく</rt></ruby>に<ruby>意味<rt>いみ</rt></ruby>はない', 'すぐ<ruby>終<rt>お</rt></ruby>わった', '<ruby>外国<rt>がいこく</rt></ruby>だけの<ruby>問題<rt>もんだい</rt></ruby>'], correctIndex: 0 },
      { question: 'マンデラが「<ruby>元看守<rt>もとかんしゅ</rt></ruby>を<ruby>昼食<rt>ちゅうしょく</rt></ruby>に<ruby>招待<rt>しょうたい</rt></ruby>した」エピソードが<ruby>示<rt>しめ</rt></ruby>すものは？', choices: ['<ruby>赦<rt>ゆる</rt></ruby>しを<ruby>行動<rt>こうどう</rt></ruby>で<ruby>示<rt>しめ</rt></ruby>した', 'ただの<ruby>食事<rt>しょくじ</rt></ruby>', '<ruby>政治的<rt>せいじてき</rt></ruby>パフォーマンス', '<ruby>復讐<rt>ふくしゅう</rt></ruby>の<ruby>機会<rt>きかい</rt></ruby>'], correctIndex: 0 },
      { question: 'マンデラの<ruby>物語<rt>ものがたり</rt></ruby>から<ruby>学<rt>まな</rt></ruby>べる<ruby>最<rt>もっと</rt></ruby>も<ruby>大切<rt>たいせつ</rt></ruby>なことは？', choices: ['<ruby>赦<rt>ゆる</rt></ruby>しと<ruby>対話<rt>たいわ</rt></ruby>で<ruby>社会<rt>しゃかい</rt></ruby>は<ruby>変<rt>か</rt></ruby>えられる', '<ruby>暴力<rt>ぼうりょく</rt></ruby>で<ruby>戦<rt>たたか</rt></ruby>うべき', '<ruby>諦<rt>あきら</rt></ruby>めるべき', '<ruby>逃<rt>に</rt></ruby>げるべき'], correctIndex: 0 },
    ],
  },

  // ================================================================
  // 🎨 ダ・ヴィンチ（学習カード連動）
  // ================================================================
  davinci: {
    beginner: [
      { question: 'ダ・ヴィンチが<ruby>描<rt>か</rt></ruby>いた<ruby>世界一<rt>せかいいち</rt></ruby><ruby>有名<rt>ゆうめい</rt></ruby>な<ruby>絵<rt>え</rt></ruby>は？', choices: ['モナ・リザ', 'ひまわり', '<ruby>星月夜<rt>ほしづきよ</rt></ruby>', '<ruby>叫<rt>さけ</rt></ruby>び'], correctIndex: 0 },
      { question: 'ダ・ヴィンチは<ruby>何<rt>なん</rt></ruby>の<ruby>国<rt>くに</rt></ruby>の<ruby>人<rt>ひと</rt></ruby>？', choices: ['イタリア', 'フランス', 'スペイン', 'ドイツ'], correctIndex: 0 },
      { question: 'ダ・ヴィンチがノートに<ruby>描<rt>か</rt></ruby>いた<ruby>乗<rt>の</rt></ruby>り<ruby>物<rt>もの</rt></ruby>は？', choices: ['ヘリコプター', '<ruby>自動車<rt>じどうしゃ</rt></ruby>', '<ruby>電車<rt>でんしゃ</rt></ruby>', 'ロケット'], correctIndex: 0 },
      { question: '「<ruby>最後<rt>さいご</rt></ruby>の<ruby>晩餐<rt>ばんさん</rt></ruby>」は<ruby>何<rt>なん</rt></ruby>の<ruby>場面<rt>ばめん</rt></ruby>を<ruby>描<rt>か</rt></ruby>いた<ruby>絵<rt>え</rt></ruby>？', choices: ['キリストの<ruby>食事<rt>しょくじ</rt></ruby>', '<ruby>戦争<rt>せんそう</rt></ruby>', 'お<ruby>祭<rt>まつ</rt></ruby>り', '<ruby>結婚式<rt>けっこんしき</rt></ruby>'], correctIndex: 0 },
      { question: 'ダ・ヴィンチは<ruby>何利<rt>なにき</rt></ruby>き？', choices: ['<ruby>左利<rt>ひだりき</rt></ruby>き', '<ruby>右利<rt>みぎき</rt></ruby>き', '<ruby>両利<rt>りょうき</rt></ruby>き', 'わからない'], correctIndex: 0 },
      { question: 'ダ・ヴィンチの<ruby>作品<rt>さくひん</rt></ruby>で<ruby>未完成<rt>みかんせい</rt></ruby>が<ruby>多<rt>おお</rt></ruby>い<ruby>理由<rt>りゆう</rt></ruby>は？', choices: ['<ruby>途中<rt>とちゅう</rt></ruby>で<ruby>別<rt>べつ</rt></ruby>のことに<ruby>興味<rt>きょうみ</rt></ruby>が<ruby>移<rt>うつ</rt></ruby>った', '<ruby>下手<rt>へた</rt></ruby>だった', 'お<ruby>金<rt>かね</rt></ruby>がなかった', '<ruby>病気<rt>びょうき</rt></ruby>だった'], correctIndex: 0 },
    ],
    challenger: [
      { question: 'ダ・ヴィンチが<ruby>文字<rt>もじ</rt></ruby>を<ruby>右<rt>みぎ</rt></ruby>から<ruby>左<rt>ひだり</rt></ruby>に<ruby>書<rt>か</rt></ruby>いた<ruby>理由<rt>りゆう</rt></ruby>は？', choices: ['<ruby>読<rt>よ</rt></ruby>まれたくないメモを<ruby>隠<rt>かく</rt></ruby>すため', '<ruby>間違<rt>まちが</rt></ruby>えた', '<ruby>左利<rt>ひだりき</rt></ruby>きだから<ruby>書<rt>か</rt></ruby>きやすい', '<ruby>外国語<rt>がいこくご</rt></ruby>だから'], correctIndex: 0 },
      { question: 'モナ・リザの<ruby>大<rt>おお</rt></ruby>きさはどのくらい？', choices: ['ノートパソコンくらい', '<ruby>教室<rt>きょうしつ</rt></ruby>の<ruby>黒板<rt>こくばん</rt></ruby>くらい', '<ruby>切手<rt>きって</rt></ruby>くらい', 'ドアくらい'], correctIndex: 0 },
      { question: 'ダ・ヴィンチのノートは<ruby>何<rt>なん</rt></ruby>ページ<ruby>残<rt>のこ</rt></ruby>っている？', choices: ['<ruby>約<rt>やく</rt></ruby>7,000ページ', '<ruby>約<rt>やく</rt></ruby>100ページ', '<ruby>約<rt>やく</rt></ruby>50ページ', '<ruby>約<rt>やく</rt></ruby>10<ruby>万<rt>まん</rt></ruby>ページ'], correctIndex: 0 },
      { question: 'ダ・ヴィンチが<ruby>絵<rt>え</rt></ruby>を<ruby>描<rt>か</rt></ruby>くために<ruby>研究<rt>けんきゅう</rt></ruby>したのは？', choices: ['<ruby>人体<rt>じんたい</rt></ruby>の<ruby>構造<rt>こうぞう</rt></ruby>', '<ruby>天気<rt>てんき</rt></ruby>', '<ruby>料理<rt>りょうり</rt></ruby>', '<ruby>植物<rt>しょくぶつ</rt></ruby>だけ'], correctIndex: 0 },
      { question: 'ダ・ヴィンチの<ruby>設計図<rt>せっけいず</rt></ruby>が<ruby>実際<rt>じっさい</rt></ruby>に<ruby>発明<rt>はつめい</rt></ruby>されたのは？', choices: ['<ruby>約<rt>やく</rt></ruby>500<ruby>年後<rt>ねんご</rt></ruby>', '10<ruby>年後<rt>ねんご</rt></ruby>', 'すぐに', 'まだ<ruby>発明<rt>はつめい</rt></ruby>されていない'], correctIndex: 0 },
      { question: 'ダ・ヴィンチが<ruby>人体<rt>じんたい</rt></ruby>を<ruby>調<rt>しら</rt></ruby>べるためにやったことは？', choices: ['<ruby>遺体<rt>いたい</rt></ruby>を<ruby>解剖<rt>かいぼう</rt></ruby>した', '<ruby>絵<rt>え</rt></ruby>を<ruby>見<rt>み</rt></ruby>た', '<ruby>想像<rt>そうぞう</rt></ruby>で<ruby>描<rt>か</rt></ruby>いた', '<ruby>他<rt>ほか</rt></ruby>の<ruby>人<rt>ひと</rt></ruby>に<ruby>聞<rt>き</rt></ruby>いた'], correctIndex: 0 },
    ],
    master: [
      { question: 'ダ・ヴィンチのノート<ruby>約<rt>やく</rt></ruby>7,000ページは<ruby>全体<rt>ぜんたい</rt></ruby>のどのくらい？', choices: ['3<ruby>分<rt>ぶん</rt></ruby>の1', '<ruby>全部<rt>ぜんぶ</rt></ruby>', '<ruby>半分<rt>はんぶん</rt></ruby>', '10<ruby>分<rt>ぶん</rt></ruby>の1'], correctIndex: 0 },
      { question: 'モナ・リザをダ・ヴィンチは<ruby>死<rt>し</rt></ruby>ぬまでどうしていた？', choices: ['<ruby>持<rt>も</rt></ruby>ち<ruby>歩<rt>ある</rt></ruby>いていた', '<ruby>売<rt>う</rt></ruby>った', '<ruby>燃<rt>も</rt></ruby>やした', '<ruby>教会<rt>きょうかい</rt></ruby>に<ruby>寄付<rt>きふ</rt></ruby>した'], correctIndex: 0 },
      { question: 'ダ・ヴィンチが<ruby>解剖<rt>かいぼう</rt></ruby>した<ruby>遺体<rt>いたい</rt></ruby>の<ruby>数<rt>かず</rt></ruby>は？', choices: ['30<ruby>体以上<rt>たいいじょう</rt></ruby>', '1<ruby>体<rt>たい</rt></ruby>', '100<ruby>体<rt>たい</rt></ruby>', '<ruby>解剖<rt>かいぼう</rt></ruby>していない'], correctIndex: 0 },
      { question: 'ダ・ヴィンチのノートに<ruby>描<rt>か</rt></ruby>かれていないものは？', choices: ['ロケット', 'ヘリコプター', 'パラシュート', '<ruby>戦車<rt>せんしゃ</rt></ruby>'], correctIndex: 0 },
      { question: '「<ruby>最後<rt>さいご</rt></ruby>の<ruby>晩餐<rt>ばんさん</rt></ruby>」の<ruby>人物表現<rt>じんぶつひょうげん</rt></ruby>の<ruby>特徴<rt>とくちょう</rt></ruby>は？', choices: ['<ruby>科学的<rt>かがくてき</rt></ruby>な<ruby>観察<rt>かんさつ</rt></ruby>に<ruby>基<rt>もと</rt></ruby>づいている', '<ruby>想像<rt>そうぞう</rt></ruby>で<ruby>描<rt>か</rt></ruby>いた', '<ruby>弟子<rt>でし</rt></ruby>が<ruby>描<rt>か</rt></ruby>いた', '<ruby>写真<rt>しゃしん</rt></ruby>を<ruby>見<rt>み</rt></ruby>て<ruby>描<rt>か</rt></ruby>いた'], correctIndex: 0 },
      { question: 'ダ・ヴィンチの<ruby>心臓<rt>しんぞう</rt></ruby>のスケッチが<ruby>正<rt>ただ</rt></ruby>しいと<ruby>確認<rt>かくにん</rt></ruby>されたのは？', choices: ['500<ruby>年後<rt>ねんご</rt></ruby>', 'すぐに', '10<ruby>年後<rt>ねんご</rt></ruby>', 'まだ<ruby>確認<rt>かくにん</rt></ruby>されていない'], correctIndex: 0 },
    ],
    legend: [
      { question: 'ダ・ヴィンチが「<ruby>万能<rt>ばんのう</rt></ruby>の<ruby>天才<rt>てんさい</rt></ruby>」と<ruby>呼<rt>よ</rt></ruby>ばれる<ruby>理由<rt>りゆう</rt></ruby>は？', choices: ['<ruby>芸術<rt>げいじゅつ</rt></ruby>から<ruby>科学<rt>かがく</rt></ruby>まであらゆる<ruby>分野<rt>ぶんや</rt></ruby>で<ruby>業績<rt>ぎょうせき</rt></ruby>を<ruby>残<rt>のこ</rt></ruby>したから', '<ruby>絵<rt>え</rt></ruby>が<ruby>上手<rt>じょうず</rt></ruby>だったから', 'お<ruby>金持<rt>かねも</rt></ruby>ちだったから', '<ruby>長生<rt>ながい</rt></ruby>きしたから'], correctIndex: 0 },
      { question: 'モナ・リザの<ruby>謎<rt>なぞ</rt></ruby>が<ruby>人々<rt>ひとびと</rt></ruby>を<ruby>惹<rt>ひ</rt></ruby>きつけ<ruby>続<rt>つづ</rt></ruby>ける<ruby>理由<rt>りゆう</rt></ruby>は？', choices: ['<ruby>誰<rt>だれ</rt></ruby>なのか・なぜ<ruby>微笑<rt>ほほえ</rt></ruby>んでいるのか<ruby>答<rt>こた</rt></ruby>えが<ruby>出<rt>で</rt></ruby>ないから', '<ruby>高<rt>たか</rt></ruby>いから', '<ruby>大<rt>おお</rt></ruby>きいから', '<ruby>古<rt>ふる</rt></ruby>いから'], correctIndex: 0 },
      { question: 'ダ・ヴィンチの<ruby>発明<rt>はつめい</rt></ruby>が<ruby>当時<rt>とうじ</rt></ruby><ruby>実現<rt>じつげん</rt></ruby>しなかった<ruby>理由<rt>りゆう</rt></ruby>は？', choices: ['<ruby>技術<rt>ぎじゅつ</rt></ruby>が<ruby>追<rt>お</rt></ruby>いついていなかったから', 'お<ruby>金<rt>かね</rt></ruby>がなかったから', '<ruby>嘘<rt>うそ</rt></ruby>だったから', '<ruby>禁止<rt>きんし</rt></ruby>されていたから'], correctIndex: 0 },
      { question: 'ダ・ヴィンチにとって「<ruby>芸術<rt>げいじゅつ</rt></ruby>と<ruby>科学<rt>かがく</rt></ruby>が<ruby>一<rt>ひと</rt></ruby>つ」だった<ruby>意味<rt>いみ</rt></ruby>は？', choices: ['<ruby>正確<rt>せいかく</rt></ruby>に<ruby>描<rt>か</rt></ruby>くには<ruby>観察<rt>かんさつ</rt></ruby>と<ruby>研究<rt>けんきゅう</rt></ruby>が<ruby>必要<rt>ひつよう</rt></ruby>だから', '<ruby>同<rt>おな</rt></ruby>じ<ruby>言葉<rt>ことば</rt></ruby>だから', '<ruby>区別<rt>くべつ</rt></ruby>がなかった<ruby>時代<rt>じだい</rt></ruby>だから', '<ruby>先生<rt>せんせい</rt></ruby>に<ruby>言<rt>い</rt></ruby>われたから'], correctIndex: 0 },
      { question: 'ダ・ヴィンチのノートの3<ruby>分<rt>ぶん</rt></ruby>の2が<ruby>失<rt>うしな</rt></ruby>われたことの<ruby>意味<rt>いみ</rt></ruby>は？', choices: ['<ruby>人類<rt>じんるい</rt></ruby>は<ruby>彼<rt>かれ</rt></ruby>の<ruby>知識<rt>ちしき</rt></ruby>の<ruby>一部<rt>いちぶ</rt></ruby>しか<ruby>知<rt>し</rt></ruby>らない', '<ruby>特<rt>とく</rt></ruby>に<ruby>問題<rt>もんだい</rt></ruby>ない', 'コピーがある', 'デジタル<ruby>化<rt>か</rt></ruby>された'], correctIndex: 0 },
      { question: '<ruby>未完成<rt>みかんせい</rt></ruby>の<ruby>作品<rt>さくひん</rt></ruby>が<ruby>多<rt>おお</rt></ruby>いのに「<ruby>最高<rt>さいこう</rt></ruby>の<ruby>天才<rt>てんさい</rt></ruby>」と<ruby>呼<rt>よ</rt></ruby>ばれることの<ruby>意味<rt>いみ</rt></ruby>は？', choices: ['<ruby>完成<rt>かんせい</rt></ruby>したものだけで<ruby>圧倒的<rt>あっとうてき</rt></ruby>だったから', '<ruby>量<rt>りょう</rt></ruby>が<ruby>多<rt>おお</rt></ruby>かったから', '<ruby>有名<rt>ゆうめい</rt></ruby>だったから', '<ruby>弟子<rt>でし</rt></ruby>が<ruby>補<rt>おぎな</rt></ruby>った'], correctIndex: 0 },
    ],
  },

  // ================================================================
  // 🔥 織田信長（DECK_KEYS未登録、将来の拡張用）
  // ================================================================
  nobunaga: {
    beginner: [
      { question: '<ruby>織田信長<rt>おだのぶなが</rt></ruby>の<ruby>子<rt>こ</rt></ruby>どもの<ruby>頃<rt>ころ</rt></ruby>のあだ<ruby>名<rt>な</rt></ruby>は？', choices: ['うつけ<ruby>者<rt>もの</rt></ruby>', '<ruby>天才<rt>てんさい</rt></ruby>', '<ruby>神童<rt>しんどう</rt></ruby>', '<ruby>勇者<rt>ゆうしゃ</rt></ruby>'], correctIndex: 0 },
      { question: '<ruby>桶狭間<rt>おけはざま</rt></ruby>の<ruby>戦<rt>たたか</rt></ruby>いで<ruby>信長<rt>のぶなが</rt></ruby>が<ruby>倒<rt>たお</rt></ruby>した<ruby>相手<rt>あいて</rt></ruby>は？', choices: ['<ruby>今川義元<rt>いまがわよしもと</rt></ruby>', '<ruby>武田信玄<rt>たけだしんげん</rt></ruby>', '<ruby>上杉謙信<rt>うえすぎけんしん</rt></ruby>', '<ruby>豊臣秀吉<rt>とよとみひでよし</rt></ruby>'], correctIndex: 0 },
      { question: '<ruby>信長<rt>のぶなが</rt></ruby>が<ruby>大量<rt>たいりょう</rt></ruby>に<ruby>使<rt>つか</rt></ruby>った<ruby>新<rt>あたら</rt></ruby>しい<ruby>武器<rt>ぶき</rt></ruby>は？', choices: ['<ruby>鉄砲<rt>てっぽう</rt></ruby>', '<ruby>弓<rt>ゆみ</rt></ruby>', '<ruby>刀<rt>かたな</rt></ruby>', '<ruby>槍<rt>やり</rt></ruby>'], correctIndex: 0 },
      { question: '<ruby>楽市楽座<rt>らくいちらくざ</rt></ruby>とは<ruby>何<rt>なに</rt></ruby>ができる<ruby>制度<rt>せいど</rt></ruby>？', choices: ['<ruby>自由<rt>じゆう</rt></ruby>に<ruby>商売<rt>しょうばい</rt></ruby>', '<ruby>自由<rt>じゆう</rt></ruby>に<ruby>旅行<rt>りょこう</rt></ruby>', '<ruby>自由<rt>じゆう</rt></ruby>に<ruby>勉強<rt>べんきょう</rt></ruby>', '<ruby>自由<rt>じゆう</rt></ruby>に<ruby>戦<rt>たたか</rt></ruby>い'], correctIndex: 0 },
      { question: '<ruby>本能寺<rt>ほんのうじ</rt></ruby>の<ruby>変<rt>へん</rt></ruby>で<ruby>信長<rt>のぶなが</rt></ruby>を<ruby>裏切<rt>うらぎ</rt></ruby>ったのは？', choices: ['<ruby>明智光秀<rt>あけちみつひで</rt></ruby>', '<ruby>豊臣秀吉<rt>とよとみひでよし</rt></ruby>', '<ruby>徳川家康<rt>とくがわいえやす</rt></ruby>', '<ruby>武田信玄<rt>たけだしんげん</rt></ruby>'], correctIndex: 0 },
    ],
    challenger: [
      { question: '<ruby>桶狭間<rt>おけはざま</rt></ruby>の<ruby>戦<rt>たたか</rt></ruby>いで<ruby>信長<rt>のぶなが</rt></ruby>の<ruby>兵<rt>へい</rt></ruby>はどのくらい？', choices: ['<ruby>約<rt>やく</rt></ruby>3<ruby>千<rt>ぜん</rt></ruby>', '<ruby>約<rt>やく</rt></ruby>3<ruby>万<rt>まん</rt></ruby>', '<ruby>約<rt>やく</rt></ruby>10<ruby>万<rt>まん</rt></ruby>', '<ruby>約<rt>やく</rt></ruby>500'], correctIndex: 0 },
      { question: '<ruby>信長<rt>のぶなが</rt></ruby>が<ruby>鉄砲<rt>てっぽう</rt></ruby>を<ruby>約<rt>やく</rt></ruby><ruby>何挺<rt>なんちょう</rt></ruby><ruby>集<rt>あつ</rt></ruby>めた？', choices: ['3,000<ruby>挺<rt>ちょう</rt></ruby>', '100<ruby>挺<rt>ちょう</rt></ruby>', '10,000<ruby>挺<rt>ちょう</rt></ruby>', '500<ruby>挺<rt>ちょう</rt></ruby>'], correctIndex: 0 },
      { question: '<ruby>楽市楽座<rt>らくいちらくざ</rt></ruby>で<ruby>信長<rt>のぶなが</rt></ruby>はどうなった？', choices: ['<ruby>他<rt>ほか</rt></ruby>の<ruby>大名<rt>だいみょう</rt></ruby>より<ruby>豊<rt>ゆた</rt></ruby>かになった', '<ruby>貧乏<rt>びんぼう</rt></ruby>になった', '<ruby>何<rt>なに</rt></ruby>も<ruby>変<rt>か</rt></ruby>わらなかった', '<ruby>追放<rt>ついほう</rt></ruby>された'], correctIndex: 0 },
      { question: '<ruby>信長<rt>のぶなが</rt></ruby>が<ruby>本能寺<rt>ほんのうじ</rt></ruby>でつぶやいたと<ruby>言<rt>い</rt></ruby>われる<ruby>言葉<rt>ことば</rt></ruby>は？', choices: ['<ruby>是非<rt>ぜひ</rt></ruby>に<ruby>及<rt>およ</rt></ruby>ばず', '<ruby>天下統一<rt>てんかとういつ</rt></ruby>', '<ruby>無念<rt>むねん</rt></ruby>', 'さようなら'], correctIndex: 0 },
      { question: '<ruby>光秀<rt>みつひで</rt></ruby>の<ruby>天下<rt>てんか</rt></ruby>は<ruby>何日間<rt>なんにちかん</rt></ruby>と<ruby>言<rt>い</rt></ruby>われる？', choices: ['<ruby>約<rt>やく</rt></ruby>13<ruby>日<rt>にち</rt></ruby>', '<ruby>約<rt>やく</rt></ruby>100<ruby>日<rt>にち</rt></ruby>', '<ruby>約<rt>やく</rt></ruby>3<ruby>年<rt>ねん</rt></ruby>', '<ruby>約<rt>やく</rt></ruby>1<ruby>日<rt>にち</rt></ruby>'], correctIndex: 0 },
    ],
    master: [
      { question: '<ruby>桶狭間<rt>おけはざま</rt></ruby>の<ruby>戦<rt>たたか</rt></ruby>いで<ruby>信長<rt>のぶなが</rt></ruby>が<ruby>利用<rt>りよう</rt></ruby>したのは？', choices: ['<ruby>嵐<rt>あらし</rt></ruby>', '<ruby>夜<rt>よる</rt></ruby>の<ruby>闇<rt>やみ</rt></ruby>', '<ruby>雪<rt>ゆき</rt></ruby>', '<ruby>霧<rt>きり</rt></ruby>'], correctIndex: 0 },
      { question: '<ruby>信長<rt>のぶなが</rt></ruby>が<ruby>大量<rt>たいりょう</rt></ruby>の<ruby>鉄砲<rt>てっぽう</rt></ruby>を<ruby>買<rt>か</rt></ruby>えた<ruby>理由<rt>りゆう</rt></ruby>は？', choices: ['<ruby>楽市楽座<rt>らくいちらくざ</rt></ruby>で<ruby>儲<rt>もう</rt></ruby>けた<ruby>経済力<rt>けいざいりょく</rt></ruby>', '<ruby>外国<rt>がいこく</rt></ruby>からの<ruby>援助<rt>えんじょ</rt></ruby>', '<ruby>盗<rt>ぬす</rt></ruby>んだ', '<ruby>親<rt>おや</rt></ruby>の<ruby>遺産<rt>いさん</rt></ruby>'], correctIndex: 0 },
      { question: '<ruby>信長<rt>のぶなが</rt></ruby>の<ruby>子<rt>こ</rt></ruby>どもの<ruby>頃<rt>ころ</rt></ruby>の<ruby>行動<rt>こうどう</rt></ruby>で<ruby>有名<rt>ゆうめい</rt></ruby>なのは？', choices: ['<ruby>裸<rt>はだか</rt></ruby>で<ruby>町<rt>まち</rt></ruby>を<ruby>走<rt>はし</rt></ruby>り<ruby>回<rt>まわ</rt></ruby>っていた', '<ruby>本<rt>ほん</rt></ruby>ばかり<ruby>読<rt>よ</rt></ruby>んでいた', '<ruby>山<rt>やま</rt></ruby>にこもっていた', '<ruby>勉強<rt>べんきょう</rt></ruby>が<ruby>得意<rt>とくい</rt></ruby>だった'], correctIndex: 0 },
      { question: '<ruby>楽市楽座<rt>らくいちらくざ</rt></ruby>は<ruby>今<rt>いま</rt></ruby>でいうと<ruby>何<rt>なに</rt></ruby>と<ruby>同<rt>おな</rt></ruby>じ<ruby>考<rt>かんが</rt></ruby>え<ruby>方<rt>かた</rt></ruby>？', choices: ['<ruby>規制緩和<rt>きせいかんわ</rt></ruby>', '<ruby>増税<rt>ぞうぜい</rt></ruby>', '<ruby>鎖国<rt>さこく</rt></ruby>', '<ruby>軍事強化<rt>ぐんじきょうか</rt></ruby>'], correctIndex: 0 },
      { question: '<ruby>光秀<rt>みつひで</rt></ruby>の<ruby>天下<rt>てんか</rt></ruby>が「<ruby>三日天下<rt>みっかてんか</rt></ruby>」と<ruby>呼<rt>よ</rt></ruby>ばれるが<ruby>実際<rt>じっさい</rt></ruby>は？', choices: ['<ruby>約<rt>やく</rt></ruby>13<ruby>日間<rt>にちかん</rt></ruby>', '<ruby>本当<rt>ほんとう</rt></ruby>に3<ruby>日間<rt>にちかん</rt></ruby>', '<ruby>約<rt>やく</rt></ruby>30<ruby>日間<rt>にちかん</rt></ruby>', '<ruby>約<rt>やく</rt></ruby>1<ruby>年間<rt>ねんかん</rt></ruby>'], correctIndex: 0 },
    ],
    legend: [
      { question: '<ruby>桶狭間<rt>おけはざま</rt></ruby>の<ruby>戦<rt>たたか</rt></ruby>いが「<ruby>日本史最大<rt>にほんしさいだい</rt></ruby>の<ruby>番狂<rt>ばんくる</rt></ruby>わせ」と<ruby>言<rt>い</rt></ruby>われる<ruby>理由<rt>りゆう</rt></ruby>は？', choices: ['<ruby>兵力差<rt>へいりょくさ</rt></ruby>が<ruby>約<rt>やく</rt></ruby>8<ruby>倍<rt>ばい</rt></ruby>もあったから', '<ruby>信長<rt>のぶなが</rt></ruby>が<ruby>弱<rt>よわ</rt></ruby>かったから', '<ruby>偶然<rt>ぐうぜん</rt></ruby><ruby>勝<rt>か</rt></ruby>ったから', '<ruby>外国<rt>がいこく</rt></ruby>が<ruby>助<rt>たす</rt></ruby>けたから'], correctIndex: 0 },
      { question: '<ruby>鉄砲<rt>てっぽう</rt></ruby>が<ruby>戦<rt>たたか</rt></ruby>い<ruby>方<rt>かた</rt></ruby>を<ruby>変<rt>か</rt></ruby>えた<ruby>最大<rt>さいだい</rt></ruby>のポイントは？', choices: ['<ruby>一騎討<rt>いっきう</rt></ruby>ちから<ruby>集団戦<rt>しゅうだんせん</rt></ruby>になった', '<ruby>音<rt>おと</rt></ruby>が<ruby>大<rt>おお</rt></ruby>きかった', '<ruby>煙<rt>けむり</rt></ruby>が<ruby>出<rt>で</rt></ruby>た', '<ruby>重<rt>おも</rt></ruby>かった'], correctIndex: 0 },
      { question: '<ruby>信長<rt>のぶなが</rt></ruby>が「うつけ<ruby>者<rt>もの</rt></ruby>」から<ruby>天下人<rt>てんかびと</rt></ruby>になれた<ruby>理由<rt>りゆう</rt></ruby>は？', choices: ['<ruby>誰<rt>だれ</rt></ruby>よりも<ruby>先<rt>さき</rt></ruby>を<ruby>見<rt>み</rt></ruby>ていたから', '<ruby>力<rt>ちから</rt></ruby>が<ruby>強<rt>つよ</rt></ruby>かったから', '<ruby>運<rt>うん</rt></ruby>が<ruby>良<rt>よ</rt></ruby>かったから', '<ruby>家<rt>いえ</rt></ruby>が<ruby>裕福<rt>ゆうふく</rt></ruby>だったから'], correctIndex: 0 },
      { question: '<ruby>楽市楽座<rt>らくいちらくざ</rt></ruby>が400<ruby>年前<rt>ねんまえ</rt></ruby>に<ruby>実行<rt>じっこう</rt></ruby>されたことのすごさは？', choices: ['<ruby>現代<rt>げんだい</rt></ruby>の<ruby>経済政策<rt>けいざいせいさく</rt></ruby>と<ruby>同<rt>おな</rt></ruby>じ<ruby>考<rt>かんが</rt></ruby>えを<ruby>先取<rt>さきど</rt></ruby>りした', '<ruby>特<rt>とく</rt></ruby>にすごくない', '<ruby>他<rt>ほか</rt></ruby>の<ruby>国<rt>くに</rt></ruby>もやっていた', '<ruby>偶然<rt>ぐうぜん</rt></ruby>うまくいった'], correctIndex: 0 },
      { question: '「<ruby>是非<rt>ぜひ</rt></ruby>に<ruby>及<rt>およ</rt></ruby>ばず」の<ruby>意味<rt>いみ</rt></ruby>は？', choices: ['<ruby>仕方<rt>しかた</rt></ruby>のないことだ', '<ruby>絶対<rt>ぜったい</rt></ruby>に<ruby>許<rt>ゆる</rt></ruby>さない', '<ruby>逃<rt>に</rt></ruby>げろ', '<ruby>戦<rt>たたか</rt></ruby>え'], correctIndex: 0 },
    ],
  },

  // ================================================================
  // 🐺 オオカミ（DECK_KEYS未登録、将来の拡張用）
  // ================================================================
  wolf: {
    beginner: [
      { question: 'オオカミは<ruby>何<rt>なに</rt></ruby>で<ruby>暮<rt>く</rt></ruby>らす<ruby>動物<rt>どうぶつ</rt></ruby>？', choices: ['<ruby>群<rt>む</rt></ruby>れ', '<ruby>一匹<rt>いっぴき</rt></ruby>', 'ペア', '<ruby>大群<rt>たいぐん</rt></ruby>'], correctIndex: 0 },
      { question: 'ニホンオオカミは<ruby>今<rt>いま</rt></ruby>どうなっている？', choices: ['<ruby>絶滅<rt>ぜつめつ</rt></ruby>した', 'たくさんいる', '<ruby>動物園<rt>どうぶつえん</rt></ruby>にいる', '<ruby>増<rt>ふ</rt></ruby>えている'], correctIndex: 0 },
      { question: 'イエローストーンでオオカミを<ruby>戻<rt>もど</rt></ruby>したらどうなった？', choices: ['<ruby>自然<rt>しぜん</rt></ruby>が<ruby>回復<rt>かいふく</rt></ruby>した', '<ruby>何<rt>なに</rt></ruby>も<ruby>変<rt>か</rt></ruby>わらなかった', '<ruby>悪<rt>わる</rt></ruby>くなった', '<ruby>動物<rt>どうぶつ</rt></ruby>が<ruby>減<rt>へ</rt></ruby>った'], correctIndex: 0 },
      { question: '<ruby>犬<rt>いぬ</rt></ruby>の<ruby>祖先<rt>そせん</rt></ruby>は<ruby>何<rt>なに</rt></ruby>？', choices: ['オオカミ', 'キツネ', 'タヌキ', 'クマ'], correctIndex: 0 },
      { question: 'オオカミの<ruby>群<rt>む</rt></ruby>れのリーダーを<ruby>何<rt>なん</rt></ruby>と<ruby>呼<rt>よ</rt></ruby>ぶ？', choices: ['αペア', 'ボス', 'キング', 'チーフ'], correctIndex: 0 },
    ],
    challenger: [
      { question: 'オオカミの<ruby>群<rt>む</rt></ruby>れのαペアとは<ruby>実<rt>じつ</rt></ruby>は？', choices: ['お<ruby>父<rt>とう</rt></ruby>さんとお<ruby>母<rt>かあ</rt></ruby>さん', '<ruby>一番強<rt>いちばんつよ</rt></ruby>い2<ruby>匹<rt>ひき</rt></ruby>', '<ruby>一番大<rt>いちばんおお</rt></ruby>きい2<ruby>匹<rt>ひき</rt></ruby>', '<ruby>外<rt>そと</rt></ruby>から<ruby>来<rt>き</rt></ruby>た2<ruby>匹<rt>ひき</rt></ruby>'], correctIndex: 0 },
      { question: 'ニホンオオカミが<ruby>最後<rt>さいご</rt></ruby>に<ruby>確認<rt>かくにん</rt></ruby>された<ruby>年<rt>とし</rt></ruby>は？', choices: ['1905<ruby>年<rt>ねん</rt></ruby>', '2000<ruby>年<rt>ねん</rt></ruby>', '1800<ruby>年<rt>ねん</rt></ruby>', '1950<ruby>年<rt>ねん</rt></ruby>'], correctIndex: 0 },
      { question: 'イエローストーンでオオカミがいなくなったら<ruby>何<rt>なに</rt></ruby>が<ruby>増<rt>ふ</rt></ruby>えすぎた？', choices: ['<ruby>鹿<rt>しか</rt></ruby>', 'うさぎ', '<ruby>鳥<rt>とり</rt></ruby>', '<ruby>魚<rt>さかな</rt></ruby>'], correctIndex: 0 },
      { question: '<ruby>人間<rt>にんげん</rt></ruby>とオオカミが<ruby>友達<rt>ともだち</rt></ruby>になったのは<ruby>何年前<rt>なんねんまえ</rt></ruby>？', choices: ['<ruby>約<rt>やく</rt></ruby>1<ruby>万<rt>まん</rt></ruby>5<ruby>千年前<rt>せんねんまえ</rt></ruby>', '<ruby>約<rt>やく</rt></ruby>100<ruby>年前<rt>ねんまえ</rt></ruby>', '<ruby>約<rt>やく</rt></ruby>1,000<ruby>年前<rt>ねんまえ</rt></ruby>', '<ruby>約<rt>やく</rt></ruby>1<ruby>億年前<rt>おくねんまえ</rt></ruby>'], correctIndex: 0 },
      { question: 'オオカミの<ruby>群<rt>む</rt></ruby>れで<ruby>役割分担<rt>やくわりぶんたん</rt></ruby>されていることは？', choices: ['<ruby>見張<rt>みは</rt></ruby>り・<ruby>子育<rt>こそだ</rt></ruby>て・<ruby>狩<rt>か</rt></ruby>り', '<ruby>特<rt>とく</rt></ruby>にない', '<ruby>全員<rt>ぜんいん</rt></ruby><ruby>同<rt>おな</rt></ruby>じ', 'リーダーだけ<ruby>働<rt>はたら</rt></ruby>く'], correctIndex: 0 },
    ],
    master: [
      { question: '<ruby>映画<rt>えいが</rt></ruby>で<ruby>描<rt>えが</rt></ruby>かれる「<ruby>力<rt>ちから</rt></ruby>で<ruby>支配<rt>しはい</rt></ruby>するリーダー」は<ruby>実<rt>じつ</rt></ruby>は？', choices: ['<ruby>誤解<rt>ごかい</rt></ruby>', '<ruby>正<rt>ただ</rt></ruby>しい', '<ruby>昔<rt>むかし</rt></ruby>は<ruby>本当<rt>ほんとう</rt></ruby>だった', '<ruby>種類<rt>しゅるい</rt></ruby>による'], correctIndex: 0 },
      { question: '<ruby>最後<rt>さいご</rt></ruby>のニホンオオカミが<ruby>見<rt>み</rt></ruby>つかった<ruby>場所<rt>ばしょ</rt></ruby>は？', choices: ['<ruby>奈良県<rt>ならけん</rt></ruby>', '<ruby>北海道<rt>ほっかいどう</rt></ruby>', '<ruby>東京<rt>とうきょう</rt></ruby>', '<ruby>沖縄<rt>おきなわ</rt></ruby>'], correctIndex: 0 },
      { question: 'オオカミが<ruby>戻<rt>もど</rt></ruby>ったら<ruby>川<rt>かわ</rt></ruby>の<ruby>流<rt>なが</rt></ruby>れまで<ruby>変<rt>か</rt></ruby>わった<ruby>現象<rt>げんしょう</rt></ruby>の<ruby>名前<rt>なまえ</rt></ruby>は？', choices: ['<ruby>栄養<rt>えいよう</rt></ruby>カスケード', '<ruby>地殻変動<rt>ちかくへんどう</rt></ruby>', '<ruby>温暖化<rt>おんだんか</rt></ruby>', '<ruby>食物連鎖<rt>しょくもつれんさ</rt></ruby>'], correctIndex: 0 },
      { question: 'ニホンオオカミの<ruby>体長<rt>たいちょう</rt></ruby>はどのくらい？', choices: ['<ruby>約<rt>やく</rt></ruby>1m', '<ruby>約<rt>やく</rt></ruby>3m', '<ruby>約<rt>やく</rt></ruby>50cm', '<ruby>約<rt>やく</rt></ruby>5m'], correctIndex: 0 },
      { question: 'チワワからグレートデンまで<ruby>全<rt>ぜん</rt></ruby><ruby>犬種<rt>けんしゅ</rt></ruby>の<ruby>共通点<rt>きょうつうてん</rt></ruby>は？', choices: ['<ruby>全<rt>すべ</rt></ruby>てオオカミが<ruby>祖先<rt>そせん</rt></ruby>', '<ruby>全<rt>すべ</rt></ruby>て<ruby>同<rt>おな</rt></ruby>じ<ruby>大<rt>おお</rt></ruby>きさだった', '<ruby>全<rt>すべ</rt></ruby>て<ruby>日本生<rt>にほんう</rt></ruby>まれ', '<ruby>全<rt>すべ</rt></ruby>て<ruby>人工的<rt>じんこうてき</rt></ruby>に<ruby>作<rt>つく</rt></ruby>られた'], correctIndex: 0 },
    ],
    legend: [
      { question: 'オオカミがいなくなって<ruby>川<rt>かわ</rt></ruby>の<ruby>流<rt>なが</rt></ruby>れまで<ruby>変<rt>か</rt></ruby>わった<ruby>仕組<rt>しく</rt></ruby>みは？', choices: ['<ruby>鹿<rt>しか</rt></ruby>が<ruby>増<rt>ふ</rt></ruby>えすぎて<ruby>木<rt>き</rt></ruby>が<ruby>枯<rt>か</rt></ruby>れ<ruby>土壌<rt>どじょう</rt></ruby>が<ruby>流<rt>なが</rt></ruby>れた', '<ruby>偶然<rt>ぐうぜん</rt></ruby>', '<ruby>地震<rt>じしん</rt></ruby>', '<ruby>人間<rt>にんげん</rt></ruby>のせい'], correctIndex: 0 },
      { question: 'ニホンオオカミが<ruby>絶滅<rt>ぜつめつ</rt></ruby>した<ruby>根本的<rt>こんぽんてき</rt></ruby>な<ruby>原因<rt>げんいん</rt></ruby>は？', choices: ['<ruby>人間<rt>にんげん</rt></ruby>が<ruby>森<rt>もり</rt></ruby>を<ruby>切<rt>き</rt></ruby>り<ruby>開<rt>ひら</rt></ruby>き<ruby>住<rt>す</rt></ruby>む<ruby>場所<rt>ばしょ</rt></ruby>を<ruby>奪<rt>うば</rt></ruby>った', '<ruby>寒<rt>さむ</rt></ruby>さ', '<ruby>他<rt>ほか</rt></ruby>の<ruby>動物<rt>どうぶつ</rt></ruby>に<ruby>負<rt>ま</rt></ruby>けた', '<ruby>病気<rt>びょうき</rt></ruby>だけ'], correctIndex: 0 },
      { question: '「<ruby>群<rt>む</rt></ruby>れ＝<ruby>家族<rt>かぞく</rt></ruby>」というオオカミの<ruby>社会<rt>しゃかい</rt></ruby>から<ruby>人間<rt>にんげん</rt></ruby>が<ruby>学<rt>まな</rt></ruby>べることは？', choices: ['<ruby>役割分担<rt>やくわりぶんたん</rt></ruby>と<ruby>助<rt>たす</rt></ruby>け<ruby>合<rt>あ</rt></ruby>いの<ruby>大切<rt>たいせつ</rt></ruby>さ', '<ruby>力<rt>ちから</rt></ruby>が<ruby>全<rt>すべ</rt></ruby>て', '<ruby>一人<rt>ひとり</rt></ruby>が<ruby>最強<rt>さいきょう</rt></ruby>', '<ruby>競争<rt>きょうそう</rt></ruby>が<ruby>大事<rt>だいじ</rt></ruby>'], correctIndex: 0 },
      { question: 'イエローストーンの<ruby>例<rt>れい</rt></ruby>が<ruby>示<rt>しめ</rt></ruby>す「<ruby>自然<rt>しぜん</rt></ruby>は<ruby>全部<rt>ぜんぶ</rt></ruby>つながっている」の<ruby>意味<rt>いみ</rt></ruby>は？', choices: ['<ruby>一<rt>ひと</rt></ruby>つの<ruby>種<rt>しゅ</rt></ruby>がいなくなると<ruby>生態系全体<rt>せいたいけいぜんたい</rt></ruby>に<ruby>影響<rt>えいきょう</rt></ruby>する', '<ruby>関係<rt>かんけい</rt></ruby>ない', '<ruby>大<rt>おお</rt></ruby>きい<ruby>動物<rt>どうぶつ</rt></ruby>だけ<ruby>重要<rt>じゅうよう</rt></ruby>', '<ruby>植物<rt>しょくぶつ</rt></ruby>は<ruby>関係<rt>かんけい</rt></ruby>ない'], correctIndex: 0 },
      { question: '<ruby>人間<rt>にんげん</rt></ruby>がオオカミと<ruby>友達<rt>ともだち</rt></ruby>になれた<ruby>理由<rt>りゆう</rt></ruby>は？', choices: ['お<ruby>互<rt>たが</rt></ruby>いに<ruby>協力<rt>きょうりょく</rt></ruby>する<ruby>利点<rt>りてん</rt></ruby>があったから', '<ruby>人間<rt>にんげん</rt></ruby>が<ruby>強<rt>つよ</rt></ruby>かったから', 'オオカミが<ruby>弱<rt>よわ</rt></ruby>かったから', '<ruby>偶然<rt>ぐうぜん</rt></ruby>'], correctIndex: 0 },
    ],
  },
};
